khoj-ai/khoj

- README.org
- src/main.py
- src/search_type/asymmetric.py
- src/search_type/image_search.py
- tests/conftest.py
- tests/test_client.py
- Miscellaneous fixes to address failing unit tests. 
- Set default value of verbose flags to various initialization methods to `False`
- Add instructions in `README.org` for installing `exiftool` (specific to Ubuntu)
Addresses #11 .
There is still one failing unit tests. Details in issue above.
> Fix Unit Tests

- tests/test_client.py
Image search doesn't always return expected image path.
Should resolve remaining issues with failing cloud test. See #11
> Skip Flaky Image Search Test

- sample_config.yml
- src/main.py
- src/search_type/asymmetric.py
- src/search_type/image_search.py
- src/search_type/symmetric_ledger.py
- src/utils/cli.py
- src/utils/helpers.py
- src/utils/rawconfig.py
- tests/conftest.py
- tests/test_asymmetric_search.py
- tests/test_client.py
- tests/test_image_search.py
- Improve application startup time
- Startup application and perform semantic search even if user offline
- Use search model config in YAML file for all search types (asymmetric, symmetric, image)
- Load search models from disk when available
- Use search model config specified in YAML file
- Add search config for Symmetric Search used by Ledger/Beancount transaction search
> Save Search Models to Disk on First Run

- src/search_type/asymmetric.py
- src/search_type/image_search.py
- src/search_type/symmetric_ledger.py
- src/utils/rawconfig.py
- tests/conftest.py
- tests/test_asymmetric_search.py
- tests/test_client.py
- tests/test_image_search.py
- Naming convention - `[ContentType]` `[ConfigType]`Config
- Where `[ConfigType]` ~ Content, Search, Processor
- Where `[ContentType]` ~ Text, Image, Asymmetric, Symmetric, Conversation
- Current Configs:
- Content:
- Org Notes
- Org Music
- Image
- Ledger/Beancount
- Search:
- Asymmetric
- Symmetric
- Image
- Processor:
- Conversation
> Rename RawConfig Types for Consistency

- Dockerfile
- README.org
- docker-compose.yml
- docker_sample_config.yml
- sample_config.yml
- src/utils/rawconfig.py
- Add a Dockerfile which builds from the `continuumio/miniconda3` image
- Installs system-level dependencies (such as exiftool)
- Performs Conda environment setup required to run the semantic-search application
- Add a docker-compose.yml
- Exposes application on port 8000 and passes the program arguments (e.g., `port`, `host`, `config`)
- Mounts the files to be indexed into volumes in the Docker image 
- Add relevant comments for documentation and rationale for why the files are setup in the way they are
Tested locally. To run:
- Checkout the branch and modify the file paths to match your local directories in `docker-compose.yml`
- Run `docker-compose up` from the root directory
- The application should be hosted on http://localhost:8000/ and can be run as usual
Closes #20
**NOTE**: I …
> Add Docker support to semantic-search

- src/main.py
- src/search_type/asymmetric.py
- tests/test_asymmetric_search.py
- Explicit filtering was being done after search by the bi-encoder
but before re-ranking by the cross-encoder
- This limited the quality of results being returned for queries with explicit filters. 
The bi-encoder returned results which were going to be excluded. 
So the burden of improving those limited results post filtering was on the
cross-encoder, by re-ranking the remaining results to best match the query
- Given that the entry and its embedding are at the same index in their respective lists. 
We know which entries map to which embedding tensors.
So we can run the filter for blocked, required words before the bi-encoder search. 
And limit entries, embeddings being considered for the current query
- Semantic search by the bi-encoder returns the most relevant results 
for the query, …
> Run Explicit Filter on Entries, Embeddings before Semantic Search for Query

- config/environment.yml
- src/main.py
- src/search_filter/date_filter.py
- src/search_filter/explicit_filter.py
- tests/test_date_filter.py
Goal
--
Allow Limiting Search to Entries in Specified Date Range
Example Queries:
---
- _Traveled for work internationally dt>"2 years ago"_
Finds relevant notes since start of 2020
- _Learnt a cool new skill dt="last month"_ 
Finds relevant notes anytime in the last month
- _Filed my taxes dt>="Jan 1984" dt<="April 1984"_ 
Any tax related notes between 1st Jan 1984 to 30th April of 1984
Details
--
- Parse natural language dates in query into date ranges
- Use `dateparser` library to parse natural language dates. But tune results to return more natural date ranges
- Example: A user asking for entries from April, requires looking for entries in the whole of April, not April 1st or April 30th
- Find all dates in entry (currently limited to YYYY-MM-DD format)
- Only perform semantic search …
> Add Date Range Filter to Search

- src/interface/web/index.html
- src/utils/cli.py
- src/utils/helpers.py
- tests/test_cli.py
- Previously we were statically populating types dropdown field in the web interface with all available search types
- This change populates the type dropdown field with only search types that are enabled/configured
- It queries the `/config` backend API to see which of the available search types are configured
> Populate type dropdown with only enabled search types on the web interface

- .dockerignore
- .github/workflows/build.yml
- .github/workflows/publish.yml
- .github/workflows/test.yml
- .gitignore
- Dockerfile
- MANIFEST.in
- config/khoj_sample.yml
- docker-compose.yml
- setup.py
- Make Github Workflows use `pip` instead of `conda`
- Publish Khoj as Python Package Automatically
- Version based on [PEP440](https://peps.python.org/pep-0440/) and [Semantic Versioning](https://semver.org/) specs
- On Push to Master: Publish a pre-release (alpha) to PyPI
- On Push to PR: Publish a development-release on TestPyPI
- On creating a (release) tag: Publish the latest version (Major.Minor.Patch) to PyPI
- Make `Dockerfile` use `pip` to build image for Khoj. Faster, more standard flow than `conda`
- Only Build Docker Image on Push to Master
- Availability of pip package negates the need for docker image for PR testing 
- Make Docker-Compose use Docker Image published to Github Container Registry
- Default Image search to disabled. [Fix loading CLIP …
> Use Pip to setup Khoj in Docker, Github Workflows. Publish to PyPi Automatically

- src/interface/emacs/khoj.el
- Reduce time from intent to results by using reasonable defaults
- Make interactions smoother, more intuitive
- Users expect to start querying immediately. The prompt to enter search type creates unnecessary friction
- By default, search using last searched content type
- Allow user to change search type, while querying, by using keyboard shortcuts
- For reference, display keyboard shortcuts to set search-type when user initiates (incremental) search
> Do Not Prompt User to Set Search Type before Querying Khoj via Emacs

- src/interface/emacs/khoj.el
- src/main.py
- Follow standard single-hyphen in names of user customizable variables
- Set size of images results rendered in Emacs using user customizable variables
- Wait 2s, by default, before initiating re-ranking of results in Emacs interface
- Fix query timing variables from being referenced before assignment on backend
> Improve Usage of User Customizable Variables in Emacs Interface

- MANIFEST.in
- Readme.md
- src/interface/desktop/configure_screen.py
- src/utils/cli.py
- src/utils/constants.py
- src/utils/yaml.py
- tests/test_cli.py
- Handle situation where app config directory or file does not exist
- Include khoj_sample.yml in pip package to load default config from
- Create khoj config directory if it doesn't exist
- Load config from khoj_sample.yml if khoj.yml config doesn't exist
- Resolve config_file path in argument to absolute at app start
Avoids conversion to absolute path across different parts of the app
> Handle Initializing Config On First Run

- src/interface/desktop/configure_screen.py
- src/interface/desktop/file_browser.py
- src/interface/desktop/labelled_text_field.py
- src/main.py
- 6e159e6: Reload settings in separate thread to not freeze Config Screen
- 32ac1ea: Allow user to quit application from the terminal via SIGINT
- 927547d: Update Title of Configure Screen to follow "[Screen] - App" pattern
- 43301d4: Increase Width of Configure Screen
- 9baea9c: Let Input Fields Wrap. Adjust Height based on Text in Field
- b7b9611: Rename FileBrowser Button Text to "Select" instead of "Add"
- Reduce user confusion on how to add multiple files per content type
- a1c58a9: Create a reusable class for the Conversation Label+Text Input Field
> Improve Configure Screen on Desktop Interface

- src/interface/desktop/configure_screen.py
- src/main.py
- What
- Add Button to Open Search Interface on Web in "Configure Screen"
- Provides GUI affordance for opening search interface to Linux users
- On Linux
- Show Configure Screen, even if not first run experience
- Do no show system tray on Linux
- Quit app on closing Configure Screen
- On Windows, Mac
- Show Configure screen only if first run experience
- Show system tray always
- Do not quit app on closing Configure Screen
- Why
- Configure screen is the only GUI element on Linux. So closing it
should close the application
- On Windows, Mac the system tray exists, so app should not be closed
on closing configure screen
> Update GUI to Handle No System Tray on Linux

- .github/workflows/release.yml
- Khoj.spec
- On Debian
- `libtorch_cuda.so` (1Gb) and `libtorch_cpu.so` (700Mb) are large shared libs
- They are available at package root and under `torch/lib` directory in the package
- We remove the unused, duplicate libraries from under `torch/lib` as only the top level libraries are used
- On Mac
- Remove `libtorch_{cpu,python}.dylib` under `torch/lib` directory from the Mac app.
- **Debian amd64** app size by **42%** from **1.6Gb to 920Mb**  
- **Mac arm64** app by **15%** from **190Mb to 160Mb**
- **Mac amd64** app by **33%** from **340Mb to 230Mb**
- [Release Workflow Run](https://github.com/debanjum/khoj/actions/runs/2878104171) after changes
- [Release Workflow Run](https://github.com/debanjum/khoj/actions/runs/2869906116) before changes
> Reduce Debian, Mac App Size by Removing Unused Libraries under Torch/Lib

- setup.py
- src/configure.py
- src/router.py
- src/search_type/text_search.py
- src/utils/helpers.py
- src/utils/state.py
- tests/conftest.py
- tests/test_client.py
- tests/test_image_search.py
- Load Models and Embeddings onto GPU if available
- Use MPS for GPU acceleration when available
- Note: Support for [MPS](https://developer.apple.com/metal/) in Pytorch is currently in v1.13.0 nightly builds. See [Announcement](https://pytorch.org/blog/introducing-accelerated-pytorch-training-on-mac/)
- Users will have to wait for PyTorch MPS support to land in stable builds
- Until then code can be tuned and tested for GPU acceleration on newer Macs
- Re-enable Tests for Image Search
> Use MPS, CUDA to GPU Accelerate Query Performance

- src/configure.py
- src/router.py
- src/search_filter/date_filter.py
- src/search_filter/explicit_filter.py
- src/search_type/text_search.py
- src/utils/config.py
- src/utils/helpers.py
- tests/conftest.py
- tests/test_client.py
- tests/test_date_filter.py
- tests/test_explicit_filter.py
- tests/test_helpers.py
- tests/test_text_search.py
- Improve explicit filter latency to work better with incremental search
- Deleting entries to be excluded from existing list of entries, embeddings
- Explicit filtering on partial words during incremental search
- Creating word set for all entries on the fly during query
- Deep copying of entries, embeddings before applying filter
- **Major**
- 191a656 Use word to entry map, list comprehension to speed up explicit filter
- Use list comprehension and `torch.index_select` methods
- to speed selection of entries, embedding tensors satisfying filter
- avoid deep copy and direct manipulation of entries, embeddings
- Use word to entry map and set operations to mark entries 
satisfying inclusion, exclusion filters
- c7de57b Pre-compute entry word sets to improve explicit filter query …
> Improve Latency of Explicit Filter

- .gitignore
- Readme.md
- src/configure.py
- src/processor/org_mode/org_to_jsonl.py
- src/router.py
- src/search_filter/base_filter.py
- src/search_filter/date_filter.py
- src/search_filter/file_filter.py
- src/search_filter/word_filter.py
- src/search_type/text_search.py
- src/utils/config.py
- tests/conftest.py
- tests/test_client.py
- tests/test_date_filter.py
- tests/test_file_filter.py
- tests/test_org_to_jsonl.py
- tests/test_text_search.py
- tests/test_word_filter.py
- e441874 Create Abstract Base Class for all filters to inherit from
- 965bd05 Make search filters return entry ids satisfying filter
- 092b9e3 Setup Filters when configuring Text Search for each Search Type
- 31503e7 Do not pass embeddings in argument to `filter.apply` method as unused
- 7606724 Add file associated with each entry to entry dict in `org_to_jsonl` converter
- 1f9fd28 Create File Filter to filter files specified in query
- 7dd20d7 Pre-compute file to entry map in speed up file based filter
- 7e083d3 Cache results for file filters passed in query for faster filtering
- 2890b4c Simplify extracting entries satisfying file filter
- f930324 Rename `explicit filter` to more appropriate name `word filter`
- 3707a4c Improve date filter perf. Precompute date to entry map, Cache …
> Create File Filter. Improve, Consolidate Filter Code

- src/interface/desktop/main_window.py
- src/main.py
- 588f598 Pass empty list of `input_files` to `FileBrowser` on first run
- 3ddffdf Create config directory before setting up logging to file under it
Resolves #78
Resolves #79
Resolves #80
> Create App Directory, Fix Initialization GUI on First Run

- src/processor/org_mode/orgnode.py
- src/search_filter/word_filter.py
- src/search_type/text_search.py
- tests/conftest.py
- tests/test_org_to_jsonl.py
- tests/test_orgnode.py
- tests/test_text_search.py
- bf01a4f Use filename or "#+TITLE" as heading for 0th level content in org files
- d6bd7bf Fix initializing `OrgNode` `level` to string to parse org files
- d835467 Throw exception if no valid entries found in specified content files
- 7df39e5 Reuse search models across `pytest` sessions. Merge unused pytest fixtures
- 2dc0588 Do not normalize absolute filenames for entry links in `OrgNode`
- e00bb53 Init word filter dictionary with default value as set to simplify code
Resolves #83
> Handle Empty Org Files or Org Files with No Headings

- Readme.md
- src/configure.py
- src/processor/ledger/beancount_to_jsonl.py
- src/processor/markdown/markdown_to_jsonl.py
- src/processor/org_mode/org_to_jsonl.py
- src/processor/org_mode/orgnode.py
- src/search_filter/word_filter.py
- src/search_type/text_search.py
- src/utils/constants.py
- src/utils/helpers.py
- src/utils/jsonl.py
- tests/conftest.py
- tests/test_beancount_to_jsonl.py
- tests/test_client.py
- tests/test_markdown_to_jsonl.py
- tests/test_org_to_jsonl.py
- tests/test_orgnode.py
- tests/test_text_search.py
- tests/test_word_filter.py
- 030fab9 Support incremental update of **Markdown** entries, embeddings
- 91aac83 Support incremental update of **Beancount** transactions, embeddings
- 2f7a6af Support incremental update of **Org-Mode** entries, embeddings
- Encode embeddings for updated or new entries
- Reuse embeddings encoded for existing entries earlier
- Merge the existing and new entries and embeddings to get the updated entries, embeddings
- 91d11cc Only hash compiled entry to identify new/updated entries to update
- b9a6e80 Make OrgNode tags stable sorted to find new entries for incremental updates
- c17a0fd Do not store word filters index to file. Not necessary for now
- Encoding embeddings is the slowest step to index content
- Previously we regenerated embeddings for all entries,
even if they had existed in …
> Support Incremental Update of Entries, Embeddings for OrgMode, Markdown, Beancount Content

- src/processor/ledger/beancount_to_jsonl.py
- src/processor/markdown/markdown_to_jsonl.py
- src/processor/org_mode/org_to_jsonl.py
- src/processor/org_mode/orgnode.py
- src/search_type/text_search.py
- src/utils/rawconfig.py
- tests/test_org_to_jsonl.py
- tests/test_orgnode.py
- tests/test_text_search.py
- Set `index_heading_entries` field in `~/.khoj/khoj.yml` to `true` to index entries with empty body
- 253c9ea Set `index_heading_entries` field in `khoj.yml` to index entries with no body
- 9d369ae Fix `OrgNode` render of entries with property drawers and empty body
- 1d3b3d5 Convert field get/set methods in `OrgNode` class to `@property`
- db37e38 Create `OrgNode` `hasBody` method. Use it in `org_to_jsonl` checks
- b4878d7 Extract entries from scratch when regenerate requested
- 52e3dd9 Pass the whole `TextContentConfig` as argument to `text_to_jsonl` methods
- e951ba3 Raise exception when org file not found
Resolves #87
> Allow Indexing Heading Entries. Improve Org, TextToJsonl Parser

- src/processor/ledger/beancount_to_jsonl.py
- src/processor/markdown/markdown_to_jsonl.py
- src/processor/org_mode/org_to_jsonl.py
- src/search_type/image_search.py
- src/utils/rawconfig.py
- tests/conftest.py
- tests/data/config.yml
- tests/test_beancount_to_jsonl.py
- tests/test_markdown_to_jsonl.py
- tests/test_org_to_jsonl.py
- tests/test_text_search.py
- 536f03a Process text content files in sorted order for stable indexing
- a701ad0 Support multiple input-filters to configure content to index via `khoj.yml`
Resolves #84
> Support Multiple Input Filters to Configure Content to Index

- src/interface/emacs/khoj.el
In my installation, it appears that `url-request-method` is sometimes set globally to POST.  Need to explicitly set it to ensure that GET is always used as intended.
> fix: explicitly set url-request-method

- src/processor/ledger/beancount_to_jsonl.py
- src/processor/markdown/markdown_to_jsonl.py
- src/processor/org_mode/org_to_jsonl.py
- src/processor/text_to_jsonl.py
- src/search_type/text_search.py
- tests/conftest.py
- tests/test_org_to_jsonl.py
- tests/test_text_search.py
There is a limit to the maximum input tokens (words) that an ML model can encode into an embedding vector.
For the models used for text search in khoj, a max token size of 256 words is appropriate [1](https://huggingface.co/sentence-transformers/multi-qa-MiniLM-L6-cos-v1#:~:text=model%20was%20just%20trained%20on%20input%20text%20up%20to%20250%20word%20pieces),[2](https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2#:~:text=input%20text%20longer%20than%20256%20word%20pieces%20is%20truncated)
Until now entries exceeding max token size would silently get truncated during embedding generation.
So the truncated portion of the entries would be ignored when matching queries with entries
This would degrade the quality of the results
- e057c8e Add method to split entries by specified max …
> Split text entries by max tokens supported by ML models

- src/interface/emacs/khoj.el
⛔ Warning (comp): khoj.el:119:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): khoj.el:120:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): khoj.el:121:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
⛔ Warning (comp): khoj.el:168:2: Warning: docstring has wrong usage of unescaped single quotes (use \= or different quoting)
> Fix usage of quotes in khoj.el docstrings

- src/configure.py
- src/processor/text_to_jsonl.py
- src/search_type/image_search.py
- src/search_type/text_search.py
- src/utils/helpers.py
- src/utils/models.py
- src/utils/rawconfig.py
- tests/test_org_to_jsonl.py
- 2fe37a0 Make type of encoder to use for embeddings configurable via `khoj.yml`
- Previously `encoder_type` was set in the setup code of search_type
- All *encoders* were of type `SentenceTransformer`
- All *cross_encoders* were of type `CrossEncoder`
- Now the `encoder_type` can be configured via the new `encoder_type` field 
in `TextSearchConfig` under `search_type` in `khoj.yml`
- All the specified `encoder-type' class needs is an `encode' method
that takes entries and returns embedding vectors
- 826f9dc Drop long words from compiled entries to be within max token limit of models
Long words (>500 characters) provide less useful context to models.
Dropping very long words allow models to create better embeddings by
passing more of the useful context from the entry to the model
- …
> Make Encoder Type Configurable. Allow using OpenAI Model for Search

- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/modal.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- b52cd85 Allow Reranking Results using Keybinding from Khoj Search Modal
- 580f4ac Add hints to Modal for available Keybindings
- da49ea2 Add placeholder text to modal in Khoj Obsidian plugin
Load Plugin but warn on failure to connect to Khoj backend.
- f046a95 Track connectedToBackend as a setting. Use it across obsidian plugin to:
- Disable command if not connected to backend
- Trigger warning notice on clicking Khoj ribbon if not connected to backend
- Show warning at top of Khoj Obsidian plugin settings pane
- 768e874 Load obsidian plugin even if fail to connect to backend but show warning
- Allows user to see reason for failure to try resolve it
- Allows user to update Khoj URL settings to point to URL of Khoj server
- 7991ab7 Add button in Obsidian plugin settings to force …
> Enhance Search Modal, Error State Handling in Khoj Obsidian Plugin

- .github/workflows/test.yml
- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- src/routers/api.py
- 1c813a6 Convert *Results Count* setting to `Slider` from `Text` in plugin settings pane
- 4e1abd1 Disable `Update` button in plugin settings while indexing vault
- 513c86c Set index file paths relative to current or default path on Khoj backend
- 4407e23 Only index current vault on Khoj. Remove `ObsidianVaultPath` setting from plugin
- 86a1e43 Return HTTP Exception on */api/update* API call failure
- 5af2b68 Update plugin notifications for errors. Remove notification for success
> Fix, Improve Configuring Khoj from Obsidian Plugin

- src/interface/web/chat.html
- src/processor/conversation/gpt.py
- src/routers/api_beta.py
- src/routers/web_client.py
- Provide a chat interface to engage with and inquire your notes
- Simplify interacting with the beta `chat` and `summarize` APIs
- Open `<khoj-url>/chat`, by default at http://localhost:8000/chat?type=summarize
- Type your queries, see summarized response by Khoj from your notes
**Note**:
- **You will need to add an API key from OpenAI to your khoj.yml**
- **Your query and top note from search result will be sent to OpenAI for processing**
- 177756b Show chat history on loading chat page on web interface
- d8ee0f0 Save chat history to disk for persistence, seeing chat logs
- 5294693 Style chat messages as speech bubbles
- d170747 Add khoj web interface and chat styling to new chat page on khoj web
- de6c146 Implement functional, unstyled chat page for khoj web interface
> Add Chat page to the Khoj Web Interface

- src/interface/emacs/khoj.el
Find items of specified type similar to current text item at point
- Support querying with text surrounding point in any text buffer
- Find similar items of specified content type indexed on Khoj
- Query using text in current section if in a `outline-mode` buffer (i.e markdown heading, org-mode entry text)
- Query using text in current paragraph if in non `outline-mode` buffer
- Search for items of `content-type` set in khoj transient menu
- Update last used khoj content-type and results from the
*find-similar* and *update* functions for later reuse
- Recently added [Find Similar Notes in Khoj Obsidian](https://github.com/debanjum/khoj/pull/122) as well
> Find Similar Notes, Transactions, Images from Khoj in Emacs

- .github/workflows/test_khoj_el.yml
- src/interface/emacs/khoj.el
- src/interface/emacs/tests/khoj-tests.el
- cffe36c Use [ERT](https://www.gnu.org/software/emacs/manual/html_node/ert/index.html) to test `khoj.el`
- cffe36c Test extracting and rendering of Org, Markdown and Ledger entries from Khoj API response
- 97e229c Automate `khoj.el` testing using Github workflow
- Improve the get text around point code for the *Find Similar* feature
- Fixes: 07e9e4e, a0b03c8
- Simplify: 0d0bf3b
- Test: 0a0f28d
> Create and Automate Tests for Khoj.el on Emacs

- .github/workflows/test.yml
- src/processor/markdown/markdown_to_jsonl.py
1. Obsidian stores markdown notes as `utf8`[1]
2. By default, the python `open` command uses the OS locale encoding[2]
So if the OS locale encoding isn't `utf8` it causes the `UnicodeDecodeError: <locale_encoding> codec can't decode byte` error
- Read markdown files as `utf8`
The Obsidian plugin is the main use-case for markdown files in khoj currently and that stores md files as `utf8`.
Do not assume utf8 for other content types like org-mode, beancount for now.
- Fail if error in reading file as utf8, instead of ignoring errors.
Would rather have user realize that their files are not going to get indexed correctly.
[1]: https://forum.obsidian.md/t/better-handle-md-files-not-stored-in-utf8-format/13524/3
[2]: https://docs.python.org/3/library/functions.html#open
> Read Markdown file as utf8 instead of the default encoding used by OS

- src/interface/obsidian/README.md
Also make it more obvious where the link is going, initially I thought the link was to another official khoj documentation site.
> Fix obsidian plugins doc link

- src/interface/emacs/khoj.el
- src/khoj/configure.py
- src/khoj/interface/web/index.html
- src/khoj/main.py
- src/khoj/processor/jsonl/jsonl_to_jsonl.py
- src/khoj/routers/api.py
- src/khoj/routers/api_beta.py
- src/khoj/utils/config.py
- src/khoj/utils/rawconfig.py
- src/khoj/utils/state.py
- tests/conftest.py
- tests/data/config.yml
- tests/test_cli.py
- tests/test_client.py
- tests/test_jsonl_to_jsonl.py
Index, Search text content not supported by default in Khoj using plugins
1. Create content plugin. It should render the source content into standardized JSONL format expected by Khoj
- JSONL is just a list of json objects separated by newline
- For khoj, each json line contains data about an entry to be indexed. E.g a markdown heading
- Each json object needs `raw`, `compiled` and `file` keys.
- The `raw` value is rendered as the search result in the interfaces 
- The `compiled` values are used to generate embeddings for search
- The `file` key can be used to jump to the result in its source file from the interfaces
2. Configure `khoj.yml` to point to the location of the plugin generated jsonl via the `input-files`, `input-filter` fields. See `tests/data/config.yml`. This is done on user …
> Enable Creating Content Plugins

- .github/workflows/test_khoj_el.yml
- src/interface/emacs/khoj.el
- src/interface/emacs/tests/khoj-tests.el
- Render conversation history in a read-only org-mode buffer for Khoj Chat
- Add `chat` as a transient action in the Khoj transient menu
- Style chat messages as org-mode entries
- Put received date in property drawer and keep it hidden/folded by default
- Add Khoj chat response as child entry of the users associated question org entry
This allows folding back-n-forth between user and Khoj for easier viewing
- Render source notes snippets used as references for response as org-mode links
Hovering mouse on link or opening links shows reference note snippets used
> Create Khoj Chat Interface in Emacs

- pyproject.toml
- src/interface/emacs/khoj.el
- src/khoj/interface/web/chat.html
- src/khoj/processor/conversation/gpt.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- tests/test_chat_actors.py
- tests/test_chat_director.py
- d78454d Load Khoj Chat buffer before asking for query to provide context
- 93e2aff Use org footnotes to add references, allows jump to def on click
- 5e9558d Stylize reference links as superscripts and show definition on hover
- bc71c19 Use `m` or `C-x m` in-buffer keybindings to send messages to Khoj
- 27217a3 Time chat API sub-components for performance analysis
- 508b217 Update Chat API, Logs, Interfaces to store, use references as list
- d4b3866 Truncate message logs to below max supported prompt size by chat model
- cf28f10 Register separate timestamps for user query and response by Khoj Chat
> Improve Khoj Chat in Emacs, Server

- src/interface/emacs/khoj.el
- src/interface/emacs/tests/khoj-tests.el
- src/khoj/routers/api.py
- src/khoj/utils/constants.py
- ae535a0 Configure Khoj chat using khoj.el by setting OpenAI API key in Emacs
- 82eb4bf Setup Khoj server on opening khoj.el
- 99d19dc Start Khoj server from Emacs using khoj.el
- c92d791 Install Khoj server from Emacs using khoj.el
*This assumes you have python (<3.11) and pip installed in a system path*
- Enable Khoj Chat by configuring you OpenAI API Key
- Specify Org Files, Directories to Index for Search (and Chat)
By default, your org-agenda-files (include archive files)) are indexed
- Invoke khoj by calling `C-c s`
``` emacs-lisp
(use-package khoj
:after org
:straight (khoj
:type git
:host github
:repo "debanjum/khoj"
:files ("src/interface/emacs/khoj.el"))
:bind ("C-c s" . 'khoj)
:config (setq
khoj-openai-api-key "<YOUR_OPENAI_API_KEY_FOR_KHOJ_CHAT>"
khoj-org-directories …
```
> Install, Start and Configure Search, Chat on Khoj Server from Emacs

- .github/workflows/dockerize_telemetry_server.yml
- src/khoj/configure.py
- src/khoj/routers/api.py
- src/khoj/utils/constants.py
- src/khoj/utils/helpers.py
- src/khoj/utils/rawconfig.py
- src/khoj/utils/state.py
- src/telemetry/Dockerfile
- src/telemetry/requirements.txt
- src/telemetry/telemetry.py
Use telemetry to better understand Khoj usage.
This will motivate and prioritize work for Khoj.
Specific questions:
- Number of active deployments of khoj server
- How regularly is khoj used (hourly, daily, weekly etc)?
- How much is which feature used (chat, search)?
- Which UI interface is used most (obsidian, emacs, web ui)?
- Expose setting to disable telemetry logging in khoj.yml
- Create basic telemetry server to log data to a DB
- Log calls to Khoj API /search, /chat, /update endpoints
- Batch upload telemetry data to server at ~hourly interval
> Add Telemetry to Understand Khoj Usage

- src/khoj/processor/conversation/utils.py
There's an assumption made in the `completion_with_backoff` method that the API key for GPT is passed in using `openai_api_key`, but most of the calling methods are using `api_key`. The code should still work if you're using an environment variable, but not if the key is passed only through the config.
Closes #220
> Use api_key keyword argument to set the openai_api_key parameter for GPT

- pyproject.toml
- src/khoj/processor/conversation/utils.py
- tests/test_conversation_utils.py
Fix the way the `truncated_message` is passed to the `ChatMessage` object in the `/chat` flow. It expects a `string`, but it's currently passing the data in a `list`.
Closes #223
> Pass truncated message as string in ChatMessage when exceeding max prompt size

- README.md
- pyproject.toml
- src/khoj/configure.py
- src/khoj/interface/desktop/labelled_text_field.py
- src/khoj/interface/desktop/main_window.py
- src/khoj/interface/web/index.html
- src/khoj/processor/github/github_to_jsonl.py
- src/khoj/processor/jsonl/jsonl_to_jsonl.py
- src/khoj/processor/ledger/beancount_to_jsonl.py
- src/khoj/processor/markdown/markdown_to_jsonl.py
- src/khoj/processor/org_mode/org_to_jsonl.py
- src/khoj/processor/pdf/pdf_to_jsonl.py
- src/khoj/processor/text_to_jsonl.py
- src/khoj/routers/api.py
- src/khoj/utils/config.py
- src/khoj/utils/constants.py
- src/khoj/utils/rawconfig.py
- tests/conftest.py
- tests/test_client.py
- tests/test_conversation_utils.py
- tests/test_text_search.py
- Requires a [classic PAT token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens)
In the future, we should setup a really easy pipeline that drives plugin configuration to the respective UIs and autogenerates a screen to set the schema.
> Add a Github plugin which can be used to read from a Github repository

- pyproject.toml
- src/khoj/interface/web/index.html
- src/khoj/processor/github/github_to_jsonl.py
> Use Github REST API and Index Commit Messages off Github Repository

- src/khoj/interface/web/chat.html
- src/khoj/interface/web/content_type_github_input.html
- src/khoj/interface/web/index.html
- src/khoj/processor/github/github_to_jsonl.py
- src/khoj/processor/markdown/markdown_to_jsonl.py
- src/khoj/processor/org_mode/org_to_jsonl.py
- src/khoj/processor/org_mode/orgnode.py
- src/khoj/routers/api.py
- src/khoj/utils/constants.py
- src/khoj/utils/rawconfig.py
- tests/conftest.py
- tests/test_orgnode.py
- Add support for indexing multiple Github repositories
- Add integration to read org files as well as markdown files in the plain text files from the repo
- Render multiple file types in the `Search` view
- Add support for configuring multiple repositories in the settings page
- [Bonus] Add additional error handling in the chat window if the user hasn't configured their settings correctly
Closes #244 and begins #245
> Support multiple Github repositories and support indexing of multiple file types

- src/khoj/routers/api.py
- src/khoj/utils/helpers.py
- Add additional request headers for `user_agent`, `referrer`, and `host`, and pull `host` from the `request.client`. These metadata should help us track any engagement for demos we setup. These fields *will not* be used for cloud-hosted instances (e.g., we can't see client IPs for users on cloud instances).
> Add additional request headers to improve telemetry

- src/khoj/interface/web/assets/khoj.css
- src/khoj/interface/web/base_config.html
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/index.html
- src/khoj/main.py
- src/khoj/processor/github/github_to_jsonl.py
- src/khoj/routers/api.py
- src/khoj/routers/web_client.py
- src/khoj/utils/cli.py
- src/khoj/utils/state.py
- Add a separate view if the instance is meant for demo purposes. This adds a banner prompting users to sign up for the waitlist and guides them to the landing page. This view also hides the settings page.
- In theory, this will be suitable for any Khoj instance that's meant for external-facing purposes (as in, outside of the user's network)
- Prevent re-indexing for Github data if this is a demo instance
- Fix up some issues with the CSS which made settings page small in mobile
- In the frontend views for Khoj, add a button to get on the waitlist and links to the landing page
> Add demo view for Khoj

- src/interface/obsidian/src/search_modal.ts
- src/interface/obsidian/src/utils.ts
- Don't add the pdf vault to the Khoj configuration if the user does not have any PDFs in their vault
- For markdown configuration, reset all preset values to follow the Obsidian vault. Eventually, we'll need to have better support for users who have an Obsidian vault and also have files outside their vault, but this should suffice for now
- If a file has no subheadings, do not try to deep link to the matching entry
> Fix configuration setup logic in Obsidian

- src/khoj/processor/pdf/pdf_to_jsonl.py
- If there's a single PDF file that has an indexing issue, the entire job fails and Khoj setup is killed. Instead, loudly log the error but continue processing.
There are additional details for the reason for this fix [in this Discord thread](https://discord.com/channels/1112065956647284756/1125330945550073876/1125550990997864550). A user was unable to index their vault due to a single failure, but also unable to pinpoint which file was causing the issue.
> Skip indexing a PDF that has a loading error

- src/interface/obsidian/package.json
- src/interface/obsidian/src/chat_modal.ts
- src/interface/obsidian/yarn.lock
- src/khoj/configure.py
- src/khoj/interface/web/chat.html
- src/khoj/processor/conversation/gpt.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- src/khoj/utils/helpers.py
- Add chat streaming to the OpenAI API request. Implement using a callback function which manages a queue where new tokens can be placed as they come on. As the thread is read from, tokens are removed.
- When the final token has been processed, add the `compiled_references` to the queue to be rendered by the `chat` client
- When the thread has been closed, save the accumulated conversation log in the user's history using a `partial func`
- Incrementally decode tokens on the front end and add them as they appear from the streamed response
- This significantly reduces perceived latency and will hopefully eliminate incident rate for timeouts
closes https://github.com/khoj-ai/khoj/issues/257
https://github.com/khoj-ai/khoj/assets/65192171/8a67ad26-0b0b-44a9-97a4-4483d7a9f642
> ⚡️ Add chat streaming to OpenAI responses

- src/khoj/configure.py
- src/khoj/main.py
- src/khoj/routers/api.py
- src/khoj/utils/constants.py
- Re-instate the scheduler, but infrequently for index updates
- In constants, determine the cadence based on whether it's a demo instance or not
- This allow us to collect telemetry again. This will also allow us to save the chat session
> Re-instate the scheduler for the demo instances

- src/interface/emacs/khoj.el
- src/interface/obsidian/src/chat_modal.ts
- src/interface/obsidian/src/settings.ts
- src/khoj/routers/api.py
- Update chat API to accept number of results to use
- Update Obsidian and Emacs clients to send number of results to use for chat
- Both Emacs, Obsidian use the existing client side results count settings
> Make Number of Results used to Generate Chat Response Configurable

- src/interface/emacs/khoj.el
- src/interface/obsidian/src/chat_modal.ts
- src/khoj/interface/web/chat.html
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- tests/test_chat_actors.py
- tests/test_chat_director.py
I'd previously split the `chat` endpoint into a separate call just for history and a separate call which streamed the response from OpenAI.
Some clients will not be able to received a streamed response. For them, keep the non-streamed response which returns a JSON object. Update the khoj.el to use the new paradigm, as well as web and Obsidian interfaces.
By default, `stream` is set to `False` and the API will return a JSON object with the raw response text and the compiled references.
Closes https://github.com/khoj-ai/khoj/issues/288
> Make streaming optional for the /chat endpoint

- src/interface/obsidian/src/utils.ts
Even when Khoj is not yet configured, we're initializing the Khoj configuration with PDFs, regardless of whether PDFs are in the vault.
Fix it to only add PDF configuration if `.pdf` files are found in the vault.
Closes #291
> [Fix] Obsidian interface setup without PDFs in vault

- src/khoj/routers/api.py
My account doesn't have gpt-4 enabled and it wouldn't work as the default value was always used from extract_questions, where the caller could use the configured model.
> Allow using configured GPT chat model

- src/khoj/configure.py
- src/khoj/routers/api.py
- src/khoj/search_type/image_search.py
- src/khoj/search_type/text_search.py
- src/khoj/utils/config.py
- src/khoj/utils/helpers.py
- src/khoj/utils/rawconfig.py
- src/khoj/utils/state.py
- tests/conftest.py
- tests/test_client.py
- tests/test_image_search.py
- tests/test_text_search.py
- Memory consumption now only scales with search models used, not with content types. 
Previously each content type had it's own copy of the search ML models. 
That'd result in 300+ Mb per enabled text content type
- Split model state into 2 separate state objects, `search_models` and `content_index`. 
This allows loading text_search and image_search models first
and then reusing them across all content_types in content_index
- The change should cut down memory utilization quite a bit for most users.
I see a >50% drop in memory utilization on my Khoj instance. 
But this will vary for each user based on the amount of content indexed vs number of plugins enabled.
- This change does not solve the RAM utilization scaling with size of the index,
as the whole content index is still kept in RAM …
> Reuse Search Models across Content Types to reduce Memory Consumption

- src/khoj/utils/cli.py
- src/khoj/utils/rawconfig.py
- 83e1088 Manage `khoj.yml` config migrations on app start. Version the `khoj.yml` schema
- 429e1b4 Regenerate index to apply corruption fixes on first run of this khoj version
Otherwise users would need to manually re-index their contents with khoj
> Create Schema Migrator and Reindex to Apply Index Corruption Fixes

- src/interface/emacs/khoj.el
otherwise it will complain for unicode characters, see https://github.com/magit/ghub/commit/1c855310909340791e5ed0410ffa6b64dbec1fed
> Encode config as utf-8 during setup in khoj.el

- pyproject.toml
- src/khoj/interface/web/config.html
- src/khoj/processor/conversation/gpt4all/chat_model.py
- src/khoj/processor/conversation/gpt4all/model_metadata.py
- src/khoj/processor/conversation/gpt4all/utils.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- src/khoj/utils/config.py
- tests/test_gpt4all_chat_actors.py
- Rather than release the first local LLM with Falcon, use Llama with the existing `GPT4All` setup.
- Rework the `extract_questions` flow. While Falcon's output wasn't high enough quality to actually use this functionality, Llama generally provides good enough responses (at least able to pass ~50% of the benchmark tests). That being said, query times might be too long to justify using this.
- Rename all references from `Falcon` -> `Llama`
- Update relevant unit tests to match Llama capability
Closes https://github.com/khoj-ai/khoj/issues/347
> Replace Falcon 🦅 model with Llama V2 🦙 for offline chat

- Khoj.spec
We have to copy the whole library for `gpt4all` into build in the `pyinstaller` spec. This change addresses that issue.
Closes https://github.com/khoj-ai/khoj/issues/355
> Fix gpt4all import error in Desktop builds

- src/interface/emacs/khoj.el
- tests/test_text_search.py
Allow enabling, disabling offline chat from Emacs during khoj setup
- Chat Options
- Enable offline chat with `(setq khoj-chat-offline t)` during khoj setup
- Offline chat models are better for privacy but not great at answering questions
- Enable online chat by setting your OpenAI API key with `(setq khoj-openai-api-key <your-openai-api-key)`
- Online chat models are better at answering but require internet
- Note: *Enabling offline chat will result in large download of Llama v2 7B model on your Khoj backend*
Related #330, #352, #359
Closes #358
> Configure using Offline Chat from Emacs

- docs/development.md
- src/khoj/interface/web/base_config.html
changed the home page reference link to `https://khoj.dev` the previous link `https://lantern.khoj.dev` does not exist.
> fixed reference link to landing page 

- .github/workflows/build_desktop.yml
- .github/workflows/pypi.yml
- .github/workflows/release.yml
- pyproject.toml
Build the Debian package using Ubuntu 20.04 instead of 22.04 as Ubuntu 20.04 comes pre-installed with `glibc_2.31` unlike Ubuntu 22.04 which uses `glibc_2.35`
Resolves #378
> Build Khoj Debian package on Ubuntu 20.04 to work with Glibc 2.31

- src/khoj/main.py
- Explicitly set locale using `locale.setLocale(locale.LC_ALL, '')` for localization. Relevant for datetime libraries. See [Python 3 documentation](https://docs.python.org/3/library/locale.html#locale.setlocale).
Should close #419
> Explicitly set Khoj to use the default locale of the user

- docs/setup.md
- src/khoj/interface/desktop/main_window.py
- src/khoj/interface/desktop/system_tray.py
- src/khoj/main.py
Previously the GUI mode (with khoj --gui or using the desktop app) would open the web interface in the users default web browser. Now the web interface is just rendered within the app itself using PyQT's Webview. This gives it a more proper app like feel
> Open Web interface within Desktop app in GUI mode

- src/khoj/interface/desktop/main_window.py
- src/khoj/main.py
- Attach the parent to the server thread, allowing the kill signal to trigger a graceful exit. Closes #442
- Investigated, Close #443 as part of this effort as well. Upon further reading, it doesn't seem necessary to use `QThreadPools`. ([see docs](https://doc.qt.io/qtforpython-5/PySide2/QtCore/QThreadPool.html)). These allow you to spin up multiple threads in the GUI layer, but the server spun up on the additional server thread should be able to create as many python threads as it needs. I'll continue evaluating this.
- I also added in support for signing packages locally in my machine, as per #440. There are no code changes, required, but documenting it here for completeness. The command to sign the package is `codesign --force --deep --sign "Developer ID Application: (Name) (ID)" …
> Sign mac app and gracefully exit GUI

- src/khoj/processor/markdown/markdown_to_jsonl.py
- src/khoj/processor/org_mode/org_to_jsonl.py
- src/khoj/processor/plaintext/plaintext_to_jsonl.py
- Skip processing a single bad markdown or plaintext file. Continue indexing the rest of the batch.
[Relevant discussion in Discord](https://discord.com/channels/1112065956647284756/1112065956647284759/1144014048015433788).
> Skip indexing single bad markdown, plaintext file

- src/khoj/interface/web/chat.html
- src/khoj/interface/web/index.html
- src/khoj/processor/conversation/gpt4all/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- tests/test_gpt4all_chat_director.py
- tests/test_openai_chat_director.py
- 613c64e Test general and notes slash commands in offline chat director tests
- 45f6959 Use general prompt when no references found and not in Notes mode
- 28d9abf Make Khoj ask clarifying questions when answer not in provided context
- 6b3e5f9 Show filtered list of commands available with the currently input text
- 204c13e Add default conversation command to auto switch b/w general, notes modes
> Add Default Command back to Chat Commands

- src/khoj/routers/api.py
- src/khoj/search_filter/base_filter.py
- src/khoj/search_filter/date_filter.py
- src/khoj/search_filter/file_filter.py
- src/khoj/search_filter/word_filter.py
- tests/test_date_filter.py
- tests/test_file_filter.py
- tests/test_gpt4all_chat_director.py
- tests/test_openai_chat_director.py
- tests/test_word_filter.py
- Allow applying word, file or date filters on your knowledge base from the chat interface
- This will limit the portion of the knowledge base Khoj chat can use to respond to your query
E.g To make khoj answers using only your work notes, ask `"Which AI product did Pablo mention? file:/notes/work/*.org"`. See [docs](https://docs.khoj.dev/#/search?id=query-filters) for reference
- 7485c39 Enable passing search query filters via chat and test it
- d5a2de6 Add method to extract filter terms from query to all filters
> Filter knowledge base used by chat to respond

- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/search_filter/date_filter.py
Suppose we have a scenario where we have notes such that the date of the note is in the filename; this is prevalent and is for example the default behavior of the Obsidian Daily Notes feature.
Chatting using a simple chat message such as "what does yesterday's note say" then fails to give relevant results, for 2 reasons:
1. By default the DateFilter uses the raw content of the entry, rather than the compiled content which includes the filename. Given how prevalent naming notes by date is, I think the DateFilter should use the compiled content.
2. The defiltered search query is then something like "Note from yesterday" which is below the score threshold because the note contents itself generally contains nothing about "yesterday" or "note". Information about the actual date should be …
> More lenient date searching

- pyproject.toml
- src/khoj/processor/conversation/gpt4all/utils.py
- src/khoj/processor/conversation/prompts.py
- tests/conftest.py
- GPT4All integration had ceased working with 0.1.7 specification. Update to use 1.0.12. At a later date, we should also use first party support for llama v2 via gpt4all
- Update the system prompt for the `extract_questions` flow to add start and end date to the yesterday date filter example.
- Update all setup data in `conftest.py` to use new client-server indexing pattern
> Bug fixes for GPT4All and extract question

- src/interface/desktop/config.html
- src/interface/desktop/main.js
- src/interface/desktop/package.json
- src/interface/desktop/preload.js
- src/interface/desktop/renderer.js
- src/interface/desktop/yarn.lock
The Desktop client was not working on Linux machines due to an incompatibility with the latest Electron version.
As it turns out, the dialog box on Windows and Linux machines do not support selection of both files or folders -- it has to be one or the other. To mitigate, add two separate buttons for adding files and folders. See attached screenshot for latest design.
Closes #489
> Fix Linux Desktop Application

- pyproject.toml
- src/khoj/routers/api.py
- Strip the incoming query from the slash command in the chat interface before sending it to the model or for search. For example, a command like "/notes where did i vist in italy?" should be fixed to "where did i visit in italy?" before 
being send for notes extraction or model response.
Closes #433
> Strip the incoming query from the slash conversation command

- pyproject.toml
- src/khoj/configure.py
- src/khoj/interface/web/config.html
- src/khoj/migrations/migrate_offline_chat_schema.py
- src/khoj/processor/conversation/gpt4all/chat_model.py
- src/khoj/processor/conversation/gpt4all/model_metadata.py
- src/khoj/processor/conversation/gpt4all/utils.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- src/khoj/utils/cli.py
- src/khoj/utils/config.py
- src/khoj/utils/rawconfig.py
- tests/conftest.py
- tests/test_gpt4all_chat_actors.py
- a85ff94 Make offline chat model user configurable. Use `filename` of any [GPT4All supported  model](https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-chat/metadata/models.json) like below:
```yml
...
processor:
conversation:
enable-offline-chat: true
offline-chat-model: wizardlm-13b-v1.1-superhot-8k.ggmlv3.q4_0.bin
...
```
- d1ff812 Run GPT4All Chat Model on GPU, when available via [GPT4All Vulcan support](https://blog.nomic.ai/posts/gpt4all-gpu-inference-with-vulkan)
- 13b16a4 Use default Llama 2 supported by GPT4All
- Make `tokenizer` and `max-prompt-size` of chat model user configurable. E.g When using chat models not in [this pre-defined list](https://github.com/khoj-ai/khoj/blob/master/src/khoj/processor/conversation/utils.py) that support larger context window or a different …
> Improve Offline Chat Model Experience

- pyproject.toml
- src/interface/desktop/main.js
- src/interface/emacs/khoj.el
- src/interface/emacs/tests/khoj-tests.el
- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- src/khoj/configure.py
- src/khoj/main.py
- src/khoj/processor/pdf/pdf_to_jsonl.py
- src/khoj/routers/api.py
- src/khoj/routers/indexer.py
- src/khoj/utils/fs_syncer.py
- src/khoj/utils/helpers.py
- tests/test_client.py
- tests/test_pdf_to_jsonl.py
- Add ability to push data to index from the Emacs, Obsidian clients
- Switch to standard mechanism of syncing files via HTTP multi-part/form. Previously we were streaming the data as JSON
- Benefits of new mechanism
- No manual parsing of files to send or receive on clients or server is required as most have in-built mechanisms to send multi-part/form requests
- The whole response is not required to be kept in memory to parse content as JSON. As individual files arrive they're automatically pushed to disk to conserve memory if required
- Binary files don't need to be encoded on client and decoded on server
- 60e9a61 Use multi-part form to receive files to index on server
- 68018ef Use multi-part form to send files to index on desktop client
- fc99431 Send files to index on server from …
> Push Files to Index from Obsidian, Emacs & Desktop Clients using Multi-Part Forms Method

- src/interface/desktop/main.js
- src/interface/obsidian/src/utils.ts
- ba60c86 Fix encoding binary files like PDFs for sync from Desktop client.
Using `readFileSync` and put content appropriately encoded `Buffer` before pushing the data mitigates the issue.
- c829399 Fix encoding binary files like PDFs for sync from Obsidian client
Use `readBinary` to read binary files like PDFs instead of plain `read`
> Fix encoding binary files for sync from the Desktop, Obsidian client

- docker-compose.yml
- pyproject.toml
Related to https://github.com/pytorch/pytorch/issues/111695, pin the pytorch version to `2.0.1` in order to avoid build issues when running the Khoj image in a Docker container.
> Pin pytorch version to 2.0.1 in order to avoid exit code 139 in Docker container

- src/khoj/processor/org_mode/org_to_entries.py
- src/khoj/processor/org_mode/orgnode.py
- tests/conftest.py
- tests/data/config.yml
- tests/data/org/interface_emacs_readme.org
- tests/data/org/main_readme.org
- tests/test_client.py
- tests/test_multiple_users.py
- tests/test_org_to_entries.py
- tests/test_orgnode.py
- tests/test_text_search.py
The parent hierarchy of org-mode entries can store important context. 
This change updates OrgNode to track parent headings for each org entry and adds the parent outline for each entry to the index
- ddb07def Test search uses ancestor headings as context for improved results
- 74403e35 Add ancestor headings of each org-mode entry to their compiled form
- 305c25ae Track ancestor headings for each org-mode entry in org-node parser
Resolves #85
> Index Parent Headings of Org-Mode Entries to Improve Search Context

- src/interface/desktop/chat.html
- src/interface/desktop/search.html
- src/khoj/app/settings.py
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/search.html
- src/khoj/main.py
- src/khoj/search_type/image_search.py
- src/khoj/search_type/text_search.py
- src/khoj/utils/rawconfig.py
- 90d463c1 Append chat message to chat logs as TextNodes in web, desktop clients
- Simplify Code to Identify Files from Github, Notion on Web, Desktop Client
- befcbcdd Use file source to find entries from github, notion on web, desktop client
- 3f0de45e Pass file source to clients via text search API response
- Make Django Logs Follow Khoj Log Format, Verbosity
- 4aec5813 Handle image search setup related warning
- b06628ee Format Django initializing outputs using Khoj logger format
- 76d041f6 Use `KHOJ_HOST` env var to set allowed/trusted domains to host Khoj
> Clean Logs, Improve Message Rendering and Make Khoj Trusted Host Configurable

- src/interface/desktop/chat.html
- src/interface/obsidian/src/chat_modal.ts
- src/interface/obsidian/styles.css
- src/khoj/interface/web/chat.html
- 5242a49a Show temporary status message when copied to clipboard
- 6d127ba1 Render chat responses as markdown in Desktop client
- 1a31a2efcf Render chat responses as markdown in chat modal of Obsidian client
- 1a31a2efcf Render references of new responses in chat modal on Obsidian client. Use new style for references
- ac292807 Properly stop mediaRecorder stream to clear microphone in-use state
- 48719ee Render newlines when references expanded in Web, Desktop and Obsidian clients
> Render Chat Responses as Markdown in Desktop, Obsidian Client

- src/khoj/database/adapters/__init__.py
If a user subscribes to Khoj with an email address that's not present in the DB, create an account with the corresponding email address and then update the Subscription object.
Bear in mind that this flow will cause some hiccups for users whose email addresses are not associated with Google accounts. So when they try to log in, their account may not be associated with their subscription. We should find better workarounds to avoid this.
> Fix null exception when user does not exist for subscription

- src/khoj/configure.py
- src/khoj/database/adapters/__init__.py
- src/khoj/interface/web/chat.html
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- Enforce limitations on how often certain conversation chat types can be used depending on whether the user is subscribed or not
- Add a rate limiter for the `/transcribe` endpoint.
> Add a ConversationCommand rate limiter for the chat endpoint

- src/interface/desktop/loading-animation.js
- src/interface/desktop/main.js
- src/khoj/interface/web/assets/utils.js
Replace `var` declarations with `let` declarations. `let` is used much more frequently in this repository.
> Replace var declarations with let declarations

- src/interface/obsidian/src/chat_modal.ts
- src/interface/obsidian/src/search_modal.ts
Users with Dataview plugin would have error as its markdown
post-processor expects the sourcePath to be a string
This prevents Khoj from responding to chat messages in the Obsidian
chat modal. Search via Obsidian still works but it throws the same
`dataview` plugin error
Pass a string as sourcePath to markdownRenderer to fix failing chat response
and stop throwing dataview errors on search
Resolves #614, Resolves #606
> Fix markdownRenderer arg to allow chat responses in Obsidian plugin

- src/interface/desktop/chat.html
- src/interface/obsidian/src/chat_modal.ts
- src/interface/obsidian/styles.css
- src/khoj/interface/web/chat.html
New default UX has 1 long-press on mobile, 2-click on desktop to send transcribed audio message
- **New Audio Chat Flow**
1. Record audio while microphone button pressed
2. Show auto-send 3s countdown timer UI for audio chat message
Provide a visual cue around send button for how long before audio
message is automatically sent to Khoj for response
3. Auto-send msg in 3s unless stop send message button clicked
- **Why** 
- Removes the previous default of 3 clicks required to send audio message
The record > stop > send process to send audio messages was unclear and effortful
- Still allows stopping message from being sent, to make correction to transcribed audio
- Removes inadvertent long audio transcriptions if forget to press stop while recording
- Refer: f0daa45a, 29a581d2, 699e9ff8
- …
> Improve Chat Input Pane Actions. Move to 1 Click Audio Chat on Mobile

- pyproject.toml
- src/khoj/interface/web/chat.html
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/helpers.py
- tests/test_gpt4all_chat_director.py
- tests/test_helpers.py
- tests/test_openai_chat_director.py
- Use [Olostep](https://www.olostep.com/) to go through top results from Serper's google search
- Add an intermediate step that summarizes extracted web results for further response downstream
- If `answerBox` is present in the query results, no need to do the additional scraping
- Add truncation logic to the model wrapper
> Scrape results from Serper results using Olostep

- src/khoj/processor/embeddings.py
Sometimes the embeddings API fails if the server is busy. Add retries in case it doesn't work the first time.
> Add retries in case the embeddings API fails

- src/interface/obsidian/package.json
- src/interface/obsidian/src/chat_modal.ts
- src/interface/obsidian/yarn.lock
- src/khoj/main.py
Removed node-fetch dependency to work on mobile. Fix CORS issue for Khoj (streaming) chat on Obsidian mobile. Verified Khoj plugin, search, chat work on Obsidian mobile.
- 04a8bbf1 Allow calls to Khoj server from Obsidian mobile app to fix CORS issue
- 447904f0 Chat stream using default `fetch' not `node-fetch' in obsidian plugin
- 00355ea9 Load chat history after other elements in chat modal on Obsidian are rendered
- b86f686c Scroll to bottom of chat modal on Obsidian across mobile & desktop
> Fix Khoj Obsidian plugin on Obsidian Mobile

- src/khoj/processor/content/notion/notion_to_entries.py
We weren't previously generating the embeddings correctly for the Notion entries. Update to resolve the embeddings logic.
Resolves https://github.com/khoj-ai/khoj/issues/637
> Fix process for generating embeddings for Notion entries

- src/interface/desktop/assets/khoj.css
- src/interface/desktop/chat.html
- src/interface/desktop/main.js
- src/interface/emacs/khoj.el
- src/interface/obsidian/src/chat_modal.ts
- src/khoj/database/adapters/__init__.py
- src/khoj/database/migrations/0030_conversation_slug_and_title.py
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/config.html
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- tests/test_gpt4all_chat_director.py
- tests/test_openai_chat_director.py
- Display `given_name` only if not `None` in config page
- Add default slugs to the migration script
- Ensure `updated_at` is saved appropriately when saving chat history
- Return most recently updated conversation as default history
- Remove bin button from the desktop, web chat interfaces
- Stop generating offline chat message on hitting a stop phrase
- Fix detecting success when indexing update succeeds on Emacs
> Miscellaneous bugs and fixes for chat sessions

- src/interface/desktop/chat.html
- src/khoj/database/adapters/__init__.py
- src/khoj/interface/web/chat.html
- Change the way conversations are being managed for requests coming from client applications
- Not all of our client apps will necessarily maintain state over the conversation IDs available to a user. For some (single-threaded conversations), it should just use a single conversation. Fix the code to do so.
> Retrieve, create, and save conversations differently for ClientApplications

- src/interface/desktop/chat.html
- src/interface/obsidian/src/chat_modal.ts
- src/khoj/interface/web/chat.html
- f8460632 Improve render of inferred query in image chat messages in Web, Desktop apps
- a2e53d5e Add inferred queries to image chat responses in Obsidian client
- 9b61f0b5 Fix rendering images from Khoj response in Obsidian client
> Fix, Improve rendering images in Obsidian, Desktop, Web clients

- src/khoj/interface/web/chat.html
- src/khoj/routers/indexer.py
- Allow users to drag/drop files into the main chat web UI to upload
- Allow users to click on the attachment icon and select a file for upload
> Support upload for files via drag/drop in the web UI

- src/interface/desktop/chat.html
- src/khoj/database/adapters/__init__.py
- src/khoj/interface/web/chat.html
- src/khoj/routers/api_chat.py
Previously deleting a chat session from the side panel on desktop, web app would sometimes result in also creating a new chat session
`get_conversation_by_user` shouldn't return new conversation if
conversation with requested id not found.
It should only return new conversation if no specific conversation
is requested and no conversations found for user at all
- Chat history load should be logged as call to that chat_history api,
not the "chat" api
- Show status updates of clearing conversation history in chat input
- Simplify web, desktop client code by removing unnecessary new variables
- Delete a new chat, this calls loadChat via window.onload which
calls server /chat/history API endpoint with conversationId set to
that of just deleted conversation sporadically
The call to GET …
> Do not create new chat session when an old chat session is deleted

- pyproject.toml
- src/interface/desktop/search.html
- src/khoj/interface/web/search.html
- src/khoj/processor/embeddings.py
- src/khoj/search_type/text_search.py
- src/khoj/utils/helpers.py
**Trigger**: SentenceTransformer Cross Encoder models now run fast on GPU enabled machines, including Mac ARM devices since UKPLab/sentence-transformers#2463
- Only call search API when pause in typing search query on web, desktop apps (44c8d093)
- Use cross-encoder to rerank search results by default on GPU machines (1105d881) and when using an inference server (53d40248)
> Rerank Search Results by Default on GPU machines

- documentation/docs/get-started/setup.mdx
- documentation/docs/miscellaneous/advanced.md
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/helpers.py
- src/khoj/utils/constants.py
- src/khoj/utils/helpers.py
- tests/test_openai_chat_actors.py
- tests/test_openai_chat_director.py
- 2e5cc49c Enforce [json mode](https://platform.openai.com/docs/guides/text-generation/json-mode) response from OpenAI chat actors prev using string lists
- 7211eb9c Use `gpt-4-turbo-preview` as default chat model, extract questions actor
- 73ad4440, f5734826 Make Khoj read khoj website to respond with accurate, up-to-date information about itself
- dd883dc5 Dedupe query in notes prompt. Improve OAI chat actor, director tests
- 70b04d16 Test data source, output mode selector, web search query chat actors
- 14682d53 Improve notes search actor to always create a non-empty list of queries
- 9a516bed Construct available data sources, output modes as a bullet list in prompts
- f28fb89a Use consistent agent name across static and dynamic examples in prompts
- f5793149 Add actor's name to …
> Improve OpenAI Chat Actors and their prompts

- src/interface/desktop/chat.html
- src/khoj/interface/web/chat.html
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- tests/test_helpers.py
- tests/test_openai_chat_actors.py
Khoj can now read website directly without needing to go through the search step first.
9974d031 Parallelize simple webpage read and extractor
81faa026 Rename extract_content online results field to web pages
50d77906 Tweak prompts to extract information from webpages, online results
83fc7d0d Test select webpage as data source and extract web urls chat actors
384db4ce Render webpage read in chat response references on Web, Desktop apps
0f9c7ede Pass multiple webpages with their urls in online results context
28d1afb1 Support webpage command in chat API
f8c23caa Add webpage chat command for read web pages requested by user
6118d1ff Create chat actor for directly reading webpages based on user message
> Allow directly reading web pages, even when SERP not enabled

- src/khoj/search_filter/date_filter.py
- tests/test_date_filter.py
- **Overview**
- Extract more structured date variants (e.g with dot(.) & slash(/) separators, 2-digit year)
- Extract some natural, partial dates as well from entries
- **Capability**
Add ability to extract the following additional date forms:
- Natural Dates: 21st April 2000, February 29 2024
- Partial Natural Dates: March 24, Mar 2024
- Structured Dates: 20/12/24, 20.12.2024, 2024/12/20
Note: *Previously only YYYY-MM-DD ISO-8601 structured date form was extracted for date filters*
- **Performance**
Using regex is MUCH faster than using `dateparser`
It's a little crude but gives acceptable performance for large datasets
> Extract More Dates from entries to improve Date Filter

- src/khoj/processor/content/markdown/markdown_to_entries.py
- src/khoj/processor/content/org_mode/org_to_entries.py
- src/khoj/processor/content/org_mode/orgnode.py
- src/khoj/processor/content/pdf/pdf_to_entries.py
- src/khoj/processor/content/plaintext/plaintext_to_entries.py
- src/khoj/processor/content/text_to_entries.py
- src/khoj/routers/api_chat.py
- tests/test_client.py
- tests/test_markdown_to_entries.py
- tests/test_multiple_users.py
- tests/test_openai_chat_actors.py
- tests/test_org_to_entries.py
- tests/test_pdf_to_entries.py
- tests/test_plaintext_to_entries.py
- tests/test_text_search.py
- 0336107f Parse markdown parent entries as single entry if fit within max tokens
- 43aaaf20 Parse markdown file as single entry if it fits with max token limits
- c093a46b Add parent heading ancestory to extracted markdown entries for context
- 73c1cc18 Chunk text in preference order of para, sentence, word, character
- 83801f83 Create wrapper function to get entries from org, md, pdf & text files
- ed6e5d1b Remove unused Entry to Jsonl converter from text to entry class, tests
- 3a103ea2 Dedupe code by using single func to process an org file into entries
Resolves #620
> Update Text Chunking Strategy to Improve Search Context

- pyproject.toml
- src/interface/desktop/main.js
- src/interface/desktop/package.json
- src/interface/desktop/yarn.lock
- src/khoj/processor/content/github/github_to_entries.py
- src/khoj/processor/content/plaintext/plaintext_to_entries.py
- src/khoj/processor/content/text_to_entries.py
- src/khoj/routers/indexer.py
- src/khoj/utils/fs_syncer.py
- src/khoj/utils/helpers.py
- tests/test_client.py
- tests/test_plaintext_to_entries.py
- fecdb28b Index all text, code files in Github repos. Not just md, org files
- acd2f39e, 814332d Send more text file types from Desktop app and improve indexing them
- 67744799 Identify file type by content & allow server to index all text files
- 4a65b4cf Stop indexing commits, issues and issue comments in a Github repo
- a600fbab Skip indexing Github repo on hitting Github API rate limit
- f040418 **Fix indexing files in sub-folders from Desktop app**
- d75767a7 Standardize structure of text to entries to match other entry processors
> Index more text file types from Desktop, Github

- pyproject.toml
- src/khoj/main.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- src/khoj/utils/state.py
- tests/test_openai_chat_actors.py
1. Detect when user intends to schedule a task, aka reminder
- Support new `reminder` output mode to the response type chat actor
- Show examples of selecting the reminder output mode to the response type chat actor
2. Extract schedule time (as cron timestring) and inferred query to run from user message
3. Use APScheduler to call chat with inferred query at scheduled time
> Support Scheduling Tasks (Reminders: Part 1)

- src/khoj/database/adapters/__init__.py
- src/khoj/processor/conversation/offline/utils.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/helpers.py
- User configured max tokens limits weren't being passed to
`send_message_to_model_wrapper`
- One of the load offline model code paths wasn't reachable. Remove it
to simplify code
- When max prompt size isn't set infer max tokens based on free VRAM
on machine
- Use min of app configured max tokens, vram based max tokens and
model context window
> Use set, inferred max token limits wherever chat models are used

- src/interface/desktop/chat.html
- src/khoj/interface/email/task.html
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/config_automation.html
- src/khoj/main.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/api.py
- src/khoj/routers/email.py
- src/khoj/routers/helpers.py
- Shutdown scheduler when application exists in prod
- Set subject dynamically when creating new tasks
- Improve UI/UX of scheduled emails
- Fix time zone in chat query history
> Fixes and improvements for scheduled tasks

- .github/workflows/pre-commit.yml
- src/interface/desktop/chat.html
- src/khoj/interface/web/chat.html
- src/khoj/processor/conversation/prompts.py
- Add parsing logic for LaTeX-format math equations in the web chat
- Add placeholder delimiters when converting the markdown to HTML in order to avoid removing the escaped characters
- Add the `<!DOCTYPE html>` specification to the page
> Add support for rendering math equations in the web view

- documentation/docs/miscellaneous/telemetry.md
I was just setting up a self-hosted Khoj and noticed that this detail was hidden in the Telemetry configuration instructions.
> Update telemetry.md disabling instructions

- src/khoj/processor/content/org_mode/org_to_entries.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- tests/conftest.py
- tests/helpers.py
- tests/test_openai_chat_actors.py
- tests/test_openai_chat_director.py
- tests/test_org_to_entries.py
- f91cdf8e Fix showing headings in intermediate step in generating chat response
- 18f7e6e7 Remove "Path" prefix from org ancestor heading in compiled entry
- dd2225b1 Use Text output mode to disambiguate from Default data source lookup
Previously if default output was selected by Khoj, we'd end up doing
a documents search as well, even when Khoj selected internet or
general data source to lookup.
This update disambiguates the default information mode from the text
output mode. To avoid doing documents search when not deemed necessary
by Khoj
- Fix openai chat actor, director unit tests
> Improve Intermediate Steps in Formulating Chat Response

- src/interface/emacs/khoj.el
- src/interface/emacs/tests/khoj-tests.el
- Khoj in Emacs Side pane
- 906ebee0 Open Khoj chat, search in right pane to allow for ambient engagement
- Improve Khoj Chat
- 14c349ac Show online references used for chat
- ad53bb52 Make chat API call async to not block user interactions
- cd4baa3f Fix loading chat history, references in khoj.el chat buffer
- Improve Khoj Search, Find Similar functions
- Make calls to Khoj search API async to not block user interactions
- e214daf9 Support Conversation Sessions
- Support opening, creating, deleting conversation sessions from the Khoj Emacs client
> Upgrade Khoj Emacs UX

- src/interface/emacs/khoj.el
- src/interface/emacs/tests/khoj-tests.el
Khoj will find and display notes similar to the current entry in the side pane when
1. find similar is open in side pane and
2. cursor has moved to a new entry
- Find similar notes to current note at cursor automatically in background
- Only show headings of search result and increase default results count
- Pass absolute path of file to index from khoj.el emacs client
- Update help message to only show the smaller set of new keybindings
- Fix edge cases in loading some chat sessions
> Automatically Find Similar Notes on Emacs in Background

- src/interface/obsidian/src/chat_view.ts
- src/interface/obsidian/src/utils.ts
- src/interface/obsidian/styles.css
- src/interface/obsidian/yarn.lock
Makes the Khoj chat plugin adapt better to the user theme, making it feel more seamless, and helps with dark mode compatibility. 
| Theme | Light | Dark |
|--|---|---|
| Default | <img width="240" alt="Khoj_Obsidian_with_Different_Themes_Default_Light" src="https://github.com/khoj-ai/khoj/assets/6413477/616bba0b-aab8-4de3-8005-8db067a5a64e"> | <img width="240" alt="Khoj_Obsidian_with_Different_Themes_Default_Dark" src="https://github.com/khoj-ai/khoj/assets/6413477/bde1958e-5114-479f-847b-544ffe12c56e"> |
|  Solarized | <img width="240" alt="Khoj_Obsidian_with_Different_Themes_Solarized_Light" src="https://github.com/khoj-ai/khoj/assets/6413477/bdd40222-b705-4dc7-b50b-653d99ce26ee"> | <img width="240" alt="Khoj_Obsidian_with_Different_Themes_Solarized_Dark" …
> Use user theme in Obsidian for Khoj plugin styling

- Dockerfile
The Khoj docker build would fail with `ImportError: libGL.so.1: cannot open shared object file: No such file or directory`. This was required by the Khoj RapidOCR python package dependency. 
<details><summary>Stacktrace</summary>
```
khoj-server-1    | Traceback (most recent call last):
khoj-server-1    |   File "/app/src/khoj/main.py", line 93, in <module>
khoj-server-1    |     from khoj.configure import configure_routes, initialize_server, configure_middleware
khoj-server-1    |   File "/app/src/khoj/configure.py", line 40, in <module>
khoj-server-1    |     from khoj.routers.indexer import configure_content, configure_search
khoj-server-1    |   File "/app/src/khoj/routers/indexer.py", line 12, in <module>
khoj-server-1    |     from khoj.processor.content.images.image_to_entries …
```
> Add system dependencies required by RapidOCR to fix Khoj Docker image

- pyproject.toml
- src/khoj/database/adapters/__init__.py
- src/khoj/processor/conversation/anthropic/anthropic_chat.py
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/offline/utils.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- tests/test_offline_chat_actors.py
- tests/test_offline_chat_director.py
- Gemma 2 is a new open model family by Google. They've released a 9B, 29B param model. A 2B model is also expected.
- It performs really well on the Chatbot arena and shows good performance when testing within Khoj as well.
- Llama.cpp support for Gemma 2 architecture seems to have stabilized
- If Gemma 2 performs well in further testing, it can be made the default offline chat model for Khoj
- Once the 2B param model is released, the model size to download can be automatically chosen based on (V)RAM available
- Support Gemma 2 for Offline Chat
- Improve and fix chat model prompts for better, consistent context
- Fix and improve offline chat actor, director tests
- Improve offline chat truncation to consider chat message delimiter tokens
> Support Gemma 2 Model Family for Offline Chat

- src/interface/web/app/components/sidePanel/chatHistorySidePanel.tsx
- src/interface/web/app/search/layout.tsx
- src/interface/web/app/search/page.tsx
- src/interface/web/app/search/search.module.css
Add a v2 search page that renders documents based on natural language queries. Search automatically when user enters query and waits for 0.75 seconds.
| Empty state | Results | No notes found |
|-|-|-|
|<img width="1078" alt="Screenshot 2024-07-25 at 13 02 57" src="https://github.com/user-attachments/assets/056e47fb-30b9-46e4-ad46-341d4662408f">|<img width="1073" alt="Screenshot 2024-07-25 at 13 01 41" src="https://github.com/user-attachments/assets/56fff4e5-61e3-4f8c-bed4-dbecdd7b4574">|<img width="1081" alt="Screenshot 2024-07-25 at 11 40 12" src="https://github.com/user-attachments/assets/9c418906-0884-4824-ae7a-dba29a158fe3">|
> Update the search page

- src/interface/emacs/khoj.el
Previously `force` was passed as a query param to the single indexing API. After the recent API updates, it is meant to select the API method to use (PATCH vs PATCH). Converting `force` argument to a bool fixes implementing this new behavior
> Fix indexing content from Emacs

- src/khoj/database/admin.py
Currently, the search model config display for admins only shows the `id` of the search model config, which is not very informative. This commit enhances the admin console by displaying the name of the search model config (`name`), as well as the bi-encoder model (`bi_encoder`) and cross-encoder model (`cross_encoder`) along the `id`.
> Improve search model config display for admin

- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
Limit file types to sync with Khoj from Obsidian to:
- Avoid hitting per user index-able data limits, especially for folks on the Khoj cloud free tier. E.g by excluding images in Obsidian vault from being synced
- Improve context used by Khoj to generate responses
Closes #893
> Set File Types to Sync from Obsidian via Khoj Plugin Settings Page

- src/interface/web/app/components/chatHistory/chatHistory.tsx
- src/interface/web/app/components/chatMessage/chatMessage.module.css
- src/interface/web/app/components/chatMessage/chatMessage.tsx
i have modified the ```chatHistory.tsx``` and added the following things:
1. `useEffect` to monitor if auto-scroll is needed
2. a button to scroll down 
1. Only auto scroll Khoj's streamed response when scroll is near bottom of page
Allows scrolling to other messages in conversation while Khoj is formulating and streaming its response
2. Add button to scroll to bottom of the chat page
3. Scroll to most recent conversation turn on conversation first load
It's a better default to anchor to most recent conversation turn (i.e most recent user message)
4. Smooth scroll when Khoj's chat response is streamed
Previously the scroll would jitter during response streaming
5. Anchor scroll position when fetch and render older messages in conversation
Allow users to keep their scroll position when …
> Only Live Scrolling when at Page Bottom and Add Button to Scroll to Page Bottom on Web App

- src/interface/web/app/agents/page.tsx
Resolves #915
So the problem was the tool tip was visible on hover, but it was slow, so before the tool tip popped up, the user would click on the button and this stopped the tool tip from popping up.
so i reduced the popup delay to 10ms. now as soon as user hovers over the button , he will see that its a feature coming soon!
> Reduce tooltip popup delay duration for Create Agent button on Web app

- src/khoj/configure.py
- src/khoj/database/adapters/__init__.py
- src/khoj/processor/image/generate.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/api_model.py
- src/khoj/routers/helpers.py
- src/khoj/utils/initialization.py
- Default to use user chat models for train of thought when no server chat settings created by admins
- Default to not create server chat settings on first run
This change simplifies switching chat models for self-hosted setups 
by just changing the chat model on the user settings page.
It falls back to use the user chat model for train of thought 
if server chat settings have not been created on the admin panel.
Server chat settings, when set, controls the chat model used 
for Khoj's train of thought and the default user chat model.
Previously a self-hosted user had to update
1. the server chat settings in the admin panel and
2. their own user chat model in the user settings panel
to completely switch to a different chat model 
for both train of thought & response generation respectively …
> Simplify switching chat model when self-hosting

- pyproject.toml
- src/khoj/processor/conversation/anthropic/anthropic_chat.py
- src/khoj/processor/conversation/anthropic/utils.py
- src/khoj/processor/conversation/google/gemini_chat.py
- src/khoj/processor/conversation/google/utils.py
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/conversation/utils.py
- src/khoj/processor/image/generate.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
Use git to capture prompt traces of khoj's train of thought. View, analyze and debug them using your favorite git client (e.g magit).
- Each commit captures an interaction with an LLM
The commit writes the query, response and system message each to a separate file in the repo.
The commit message captures the chat model, Khoj version and other metadata
- Each conversation turn can have multiple interactions with an LLM (e.g Khoj's train of thought)
- Each new conversation turn forks from and merges back into its conversation branch
- Each new conversation branches from the user branch
- Each new user branches from root commit on the main branch
1. Set `KHOJ_DEBUG=true` or start khoj in very verbose mode with `khoj -vv` to turn on prompt tracing
2. Chat with Khoj as usual 
3. Open the …
> Add Prompt Tracer to Visualize, Analyze and Debug Khoj's Train of Thought

- docker-compose.yml
- documentation/docs/features/chat.md
- documentation/docs/features/code_execution.md
- pyproject.toml
- src/interface/web/app/chat/page.tsx
- src/interface/web/app/common/chatFunctions.ts
- src/interface/web/app/common/colorUtils.ts
- src/interface/web/app/components/chatHistory/chatHistory.tsx
- src/interface/web/app/components/chatInputArea/chatInputArea.tsx
- src/interface/web/app/components/chatMessage/chatMessage.tsx
- src/interface/web/app/factchecker/page.tsx
- src/interface/web/tailwind.config.ts
- src/khoj/configure.py
- src/khoj/database/adapters/__init__.py
- src/khoj/processor/conversation/google/utils.py
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/processor/embeddings.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/routers/research.py
- src/khoj/utils/helpers.py
- Improve chat actors and their prompts for research mode.
- Add documentation to enable the code tool when self-hosting Khoj
- Edit Chat Messages
- Store Turn Id in each chat message. 
- Expose API to delete chat message.
- Expose delete chat message button to turn delete chat message from web app
- Set LLM Generation Seed for Reproducible Debugging and Testing
- Setting seed for LLM generation is supported by Llama.cpp and OpenAI models. 
This can (somewhat) restrain LLM output
- Getting fixed responses for fixed inputs helps test, debug longer reasoning chains like used in advanced reasoning
> Research Mode [Part 2]: Improve Prompts, Edit Chat Messages. Set LLM Seed for Reproducibility

- pyproject.toml
- tests/eval_frames.py
We need better, automated evals to measure performance shifts of Khoj
across prompt, model and capability changes.
Google's FRAMES benchmark evaluates multi-step retrieval and reasoning
capabilities of AI agents. It's a good starter benchmark to evaluate Khoj.
This PR adds an eval script to evaluate Khoj responses on the
the FRAMES benchmark prompts against the ground truth provided by it.
Gemini is used as an LLM Judge to auto grade Khoj responses vs ground truth 
data from the benchmark.
> Add Script to Evaluate Khoj on Google's FRAMES benchmark

- src/khoj/configure.py
- src/khoj/database/adapters/__init__.py
- src/khoj/processor/content/docx/docx_to_entries.py
- src/khoj/processor/content/github/github_to_entries.py
- src/khoj/processor/content/images/image_to_entries.py
- src/khoj/processor/content/markdown/markdown_to_entries.py
- src/khoj/processor/content/notion/notion_to_entries.py
- src/khoj/processor/content/org_mode/org_to_entries.py
- src/khoj/processor/content/pdf/pdf_to_entries.py
- src/khoj/processor/content/plaintext/plaintext_to_entries.py
- src/khoj/processor/content/text_to_entries.py
- src/khoj/routers/api.py
- src/khoj/routers/api_content.py
- src/khoj/routers/helpers.py
- src/khoj/routers/notion.py
- src/khoj/search_type/text_search.py
- src/khoj/utils/fs_syncer.py
- tests/conftest.py
- tests/test_client.py
Increase defense-in-depth by reducing paths to create, read, update or delete entries, files and conversations in DB when user is unset.
> Do not CRUD on entries, files & conversations in DB for null user

- src/khoj/database/adapters/__init__.py
This pull request addresses a database connection leak caused by `django-apscheduler` not closing stale connections after task execution. The solution involves wrapping `run_with_process_lock` with the `@close_old_connections` decorator provided by `django-apscheduler`.
For more details, refer to the [django-apscheduler documentation on database connections and timeouts](https://github.com/jcass77/django-apscheduler#database-connections-and-timeouts).
- Added `@close_old_connections` decorator to `run_with_process_lock` to ensure database connections are properly closed after each scheduled task.
- Fixes #980: Database connections not closed after scheduled tasks, leading to connection leakage.
> Fix database connections leakage (#980)

- .github/workflows/run_evals.yml
- tests/evals/eval.py
- Evaluate khoj on random 200 questions from each of google [frames](https://huggingface.co/datasets/google/frames-benchmark) and openai [simpleqa](https://openai.com/index/introducing-simpleqa/) benchmarks across *general*, *default* and *research* modes
- Run eval with Gemini 1.5 Flash as test giver and Gemini 1.5 Pro as test evaluator models
- Trigger eval workflow on release or manually
- Make dataset, khoj mode and sample size configurable when triggered via manual workflow
- Enable Web search, webpage read tools during evaluation
> Add GitHub workflow to quiz Khoj on specified evals

- .dockerignore
- .github/workflows/dockerize.yml
- Dockerfile
- prod.Dockerfile
- src/interface/web/app/agents/layout.tsx
- src/interface/web/app/chat/layout.tsx
- src/interface/web/app/fonts.ts
- src/interface/web/app/globals.css
- src/interface/web/app/layout.tsx
- src/interface/web/app/settings/layout.tsx
- src/interface/web/app/share/chat/layout.tsx
- src/interface/web/package.json
- src/interface/web/tailwind.config.ts
Improve build speed and size of khoj docker images
- Decouple web app and server build steps
- Build the web app and server in parallel
- Cache docker layers for reuse across dockerize github workflow runs
- Split Docker build layers for improved cacheability (e.g separate `yarn install` and `yarn build` steps)
- Use an up-to-date `.dockerignore` to exclude unnecessary directories
- Do not installing cuda python packages for cpu builds
- Use consistent mechanism to get fonts for web app
- Make tailwind extensions production instead of dev dependencies
- Make next.js create production builds for the web app (via `NODE_ENV=production` env var)
> Speed up Docker image builds using multi-stage parallel pipelines

- pyproject.toml
- src/khoj/processor/conversation/utils.py
- src/khoj/processor/tools/run_code.py
- src/khoj/routers/research.py
- tests/test_conversation_utils.py
- Improve escaping to load complex json objects
- Fallback to a more forgiving [json5](https://json5.org/) loader if `json.loads` cannot parse complex json str
This should reduce failures to pick research tool and run code by agent
> Improve parsing complex json strings returned by LLM

- src/khoj/processor/content/markdown/markdown_to_entries.py
- src/khoj/processor/content/org_mode/org_to_entries.py
- Path with / are converted to \\ on Windows using the `Path` operator.
- The `markdown_to_entries` module was trying to normalize file paths with`Path`  for some reason.
This would store the file paths in DB Entry differently than the file to entries map if Khoj ran on Windows.
That'd result in a KeyError when trying to look up the entry file path from `file_to_text_map` in the `text_to_entries:update_embeddings()` function.
- Removing the unnecessary OS dependent Path normalization in `markdown_to_entries` should keep the file path storage consistent across `file_to_text_map` var, `FileObjectAdaptor`, `Entry` DB tables on Windows for Markdown files as well.
This issue will affect users hosting Khoj server on Windows and attempting to index markdown files.
Resolves #984
> Do not wrap filepath in Path to fix indexing markdown files on Windows

- documentation/docs/clients/emacs.md
Fixes an outdated query filters link in the emacs docs.
> Fix broken doc links to query filters

- .github/workflows/run_evals.yml
This allows code tool to be used in eval runs across sandbox crashes.
See https://github.com/khoj-ai/terrarium/commit/e3fed3750b4c9a766b2231bfc8c57a751ad0bd44 for corresponding changes to use pm2 to auto-restart code sandbox on crash.
> Restart code sandbox on crash in eval github workflow

- src/interface/web/app/automations/page.tsx
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
Previously we couldn't use research mode or use other slash commands 
in automated tasks.
This change separates determining if a chat query is triggered via
automated task from (other) conversation commands to run the query with.
This unlocks the ability to enable research mode in automations 
apart from other variations like  /image or /diagram etc
> Allow research mode and other conversation commands in automations

- src/interface/web/app/components/agentCard/agentCard.tsx
- src/interface/web/components/ui/tabs.tsx
- src/interface/web/package.json
- src/interface/web/yarn.lock
- Add support for seeing all steps of the agent modification flow via tabs at the top of the modal
- Separate knowledge base & tool selection into two separate parts
> Improve the agent management UX

- src/interface/web/app/automations/page.tsx
- src/khoj/database/adapters/__init__.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- tests/test_online_chat_actors.py
- Format AI response to send in automation email
- Let Khoj infer chat query based on user automation query
- Decide if automation emails should be sent based on response
- Fix the `to_notify_or_not` decider AI
- Ask reason before decision to improve to_notify decider AI
- Show error message on web app when fail to create/update automation
> Improve Automation Flexibility and Automation Email Format

- src/khoj/processor/conversation/openai/utils.py
- src/khoj/utils/helpers.py
OpenAI chat models deployed on Azure are (ironically) not OpenAI API compatible endpoints.
This change enables using OpenAI chat models deployed on Azure with Khoj.
> Support Azure OpenAI API endpoint as Chat Provider

- src/khoj/routers/helpers.py
This change makes Automations (and possibly other entrypoints) use the configured OpenAI-compatible server if that has been set. Without this change it tries to use the hardcoded OpenAI provider.
All the other calls in this file use a similar method to pass in the base URL.
**I have not been able to manually test this because the docker build is taking an extremely long time to build locally.**
> Use the configured OpenAI Base URL for Automations

- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/search_modal.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- src/interface/obsidian/styles.css
This PR delivers comprehensive improvements to the Khoj plugin across multiple key areas:
🔍 Search Enhancements:
- Added visual loading indicators during search operations
- Implemented color-coded results to distinguish between vault and external files
- Added abort logic for previous requests to improve performance
- Enhanced search feedback with clear status indicators
- Improved empty state handling
🔄 Synchronization Improvements:
- Added configurable sync interval setting in minutes
- Implemented manual "Sync new changes" command
- Enhanced sync timer management with automatic restart
- Improved notification system for sync operations
📁 Folder Management:
- Added granular folder selection for sync
- Implemented intuitive folder suggestion modal
- Enhanced folder list visualization
💅 …
> Enhance Khoj plugin with improved search, synchronization and folder management

- documentation/docs/advanced/lmstudio.md
`Ai Model API` instead of  `OpenAI Processor Conversation Config`
> Fix stale lmstudio documentation to set ai model api via admin panel

- src/khoj/routers/helpers.py
Handle additional HTTP redirect status code 308 in scheduled chat requests
Related to the issue #1067 after building the image with this code, worked perfectly.
> Handle additional HTTP redirect status code 308

- src/interface/web/app/search/page.tsx
- src/khoj/routers/api.py
Closes #1024
Added file path autocompletion to enhance the search experience in Khoj. Users can now easily search for specific files by typing "file:" followed by the file name, with real-time suggestions appearing as they type.
- Added new API endpoint `/api/file-suggestions` to get file path suggestions
- Enhanced search UI with dropdown suggestions for file paths
- Implemented debounced search to optimize API calls
- Added keyboard (Enter) and mouse click support for selecting suggestions
- Type "file:" to trigger file path suggestions
- Real-time filtering of suggestions as you type
- Top 10 alphabetically sorted suggestions
- Case-insensitive matching
- Keyboard and mouse interaction support
- Clear visual feedback with a dropdown UI
[Add screenshots showing the file path …
> feat: add autocomplete suggestions feature in search page

- pyproject.toml
- src/khoj/app/settings.py
Use [pgserver](https://github.com/orm011/pgserver/) python package as an embedded postgres db, installed directly as a khoj python package dependency.
This significantly simplifies self-hosting setup with just a `pip install khoj`. No need to also install postgres separately.
Still use standard postgres server for multi-user, production use-cases.
> Use embedded postgres db to simplify self-hosted setup

- src/khoj/processor/conversation/google/gemini_chat.py
- src/khoj/processor/conversation/google/utils.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/helpers.py
- Specify min, max number of list items expected in AI response via json schema enforcement
- Warn and drop invalid/empty messages when format messages for Gemini models
- Make Gemini response adhere to the order of the schema property definitions
- Improve agent creation safety checker by using response schema, better prompt
> Improve Gemini Response Reliability

- documentation/docs/advanced/admin.md
I’ve corrected a few issues in the text:
- "you admin panel" → "your admin panel".
- "It help give the agent" → "It helps give the agent".
- "It is not current used in any client app." → "It is not currently used in any client app."
These adjustments should make the text clearer and more accurate.
> Fix typos in admin panel documentation

- src/khoj/processor/content/images/image_to_entries.py
- src/khoj/routers/helpers.py
This small PR resolves the deprecation warnings on `datetime` in Python3.12+. You can find them in the [CI logs](https://github.com/khoj-ai/khoj/actions/runs/14538833837/job/40792624987#step:9:134):
```python
/__w/khoj/khoj/src/khoj/processor/content/images/image_to_entries.py:61: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
timestamp_now = datetime.utcnow().timestamp()
```
> Resolve datetime utcnow deprecation warnings

- src/khoj/database/adapters/__init__.py
- src/khoj/processor/conversation/anthropic/anthropic_chat.py
- src/khoj/processor/conversation/anthropic/utils.py
- src/khoj/processor/conversation/google/gemini_chat.py
- src/khoj/processor/conversation/google/utils.py
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- Simplify code and logic to stream chat response by solely relying on asyncio event loop. 
- Reduce overhead of managing threads to increase efficiency and throughput (where possible).
- Use async/await with no threading when generating chat response via OpenAI, Gemini, Anthropic AI model APIs 
- Use threading for offline chat model as llama-cpp doesn't support async streaming yet
> Simplify AI Chat Response Streaming

- src/khoj/app/settings.py
I was playing around with this, and ended up blowing away some data by destroying my `.venv`. 
It seems to me that it would be useful to be able to be explicit about where the embedded database should live - as well as where it _does_ live (via the info log), when not specifying.
> allow setting the directory for the embedded postgres db with PGSERVER_DATA_DIR

- src/khoj/database/models/__init__.py
- src/khoj/processor/content/markdown/markdown_to_entries.py
- src/khoj/processor/content/org_mode/org_to_entries.py
- src/khoj/processor/content/org_mode/orgnode.py
- src/khoj/processor/content/text_to_entries.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/helpers.py
- src/khoj/search_type/text_search.py
- src/khoj/utils/rawconfig.py
- tests/data/markdown/main_readme.md
- tests/data/org/main_readme.org
- tests/test_markdown_to_entries.py
- tests/test_org_to_entries.py
- tests/test_orgnode.py
Show deep link URI and raw document context to provide deeper, richer context to Khoj. This should allow it better combine semantic search with other new document retrieval tools like line range based file viewer and regex tools added in #1205 
- Attach line number based deeplinks to each indexed document entry
Document URI follows URL fragment based schema of form `file:///path/to/file.txt#line=123`
- Show raw indexed document entries with deep links to LLM when it uses the semantic search tool
- Reduce structural changes to raw org-mode entries for easier deep linking.
> Add Deeplinks to Improve Context for Document Retrieval

- src/interface/web/app/chat/page.tsx
- src/interface/web/app/components/chatInputArea/chatInputArea.tsx
- src/interface/web/package.json
- src/interface/web/yarn.lock
- src/khoj/database/adapters/__init__.py
- src/khoj/database/models/__init__.py
- src/khoj/main.py
- src/khoj/processor/conversation/utils.py
- src/khoj/processor/operator/__init__.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/routers/research.py
- src/khoj/utils/rawconfig.py
- Add a websocket api endpoint for chat. Reuse most of the existing chat logic.
- Communicate from web app using the websocket chat api endpoint.
- Pass interrupt messages using websocket to guide research, operator trajectory
Previously we were using the abort and send new POST /api/chat mechanism.
This didn't scale well to multi-worker setups as a different worker could pick up the new interrupt message request.
Using websocket to send messages in the middle of long running tasks
should work more naturally.
> Add websocket chat api to ease bi-directional communication

- tests/test_conversation_utils.py
This PR resolves the deprecation warnings of the Pydantic library, which you can find in the [CI logs](https://github.com/khoj-ai/khoj/actions/runs/16528997676/job/46749452047#step:9:142):
```python
PydanticDeprecatedSince20: The `copy` method is deprecated; use `model_copy` instead. See the docstring of `BaseModel.copy` for details about how to handle `include` and `exclude`. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/
```
> Resolve Pydantic deprecation warnings
