khoj-ai/khoj

- .github/workflows/build.yml
Refer:
- https://github.com/marketplace/actions/setup-miniconda
> Cache Conda Setup to Improve Cloud Build Time

- .github/workflows/build.yml
- Dockerfile
- README.org
- config/environment.yml
- docker-compose.yml
Addresses #26 by moving the Dockerfile out to the root directory so it has access to the folders that should be added to the working directory.
Attempts to address #28 by explicitly allocating 8GB RAM to the Docker container, thought that may not help as RAM per default machine is 7GB, according to [this post](https://github.community/t/test-in-docker-container-fails-with-error-137-indicating-a-probable-memory-leak/136048).
> Address Issues with Docker builds

- src/interface/emacs/khoj.el
- src/main.py
- src/processor/org_mode/org_to_jsonl.py
- src/search_filter/date_filter.py
- src/search_filter/explicit_filter.py
- src/search_type/text_search.py
- tests/test_asymmetric_search.py
- tests/test_client.py
- tests/test_date_filter.py
- Improve Search API Latency by ~50-100x to <100ms
- Trade-off speed for accuracy in default, fast path of /search API by not re-ranking results using cross-encoder
- Make re-ranking of results via cross-encoder configurable via new `?&r=<false|true>` query param to /search API
- Only deep-copy entries, embeddings to apply filters if query has any filter keywords
- Use default, fast path to query /search API while user is typing
- Upgrade to cross-encoder re-ranked results once user goes idle (or ends search normally)
Closes #37
> Support Incremental Search in Khoj

- .gitignore
- MANIFEST.in
- Readme.md
- setup.py
- src/main.py
- Add `setup.py` to support pip install of khoj package
- Fixup Application to work with pip install
- Update Readme with instructions to install package via pip
- Publish Khoj as `khoj-assistant` on [PyPi](https://pypi.org/project/khoj-assistant/)
> Publish Khoj on PyPi

- Khoj.spec
- src/interface/desktop/file_browser.py
- src/interface/desktop/main_window.py
- src/interface/desktop/system_tray.py
- src/utils/helpers.py
- 5e6625a Fix file browser to not add empty line when no file/dir selected
- 8098b8c Bring main window to Top when open from System Tray
- 1c122a8 Place window near top so buttons are not hidden by OS bottom bar
- dfe2546 Set Khoj Icon on Main Desktop Window
- 1b1f8f9 Move Splash screen text below icon. Set the text color to black
- 450f644 Fix path to remove shared libraries when packaging the Windows app
> Fix, Improve Desktop GUI Splash Screen and Main Window

- setup.py
- src/configure.py
- src/main.py
- src/routers/api.py
- src/utils/state.py
- c535953 Update index automatically in non GUI mode too
- 701d92e Lock the index before updating it via API or Scheduler
- 3b0783a Automate updating embeddings, search index on a hourly schedule
Resolves #106
> Automatically update search index hourly

- src/interface/emacs/khoj.el
- 5f446b1 Convert `khoj` entry point method to transient menu for richer configuration
- 9d64a00 Allow updating khoj content index from within `khoj.el`
> Use Transient Menu to Improve Khoj.el Interface

- .github/workflows/build_khoj_el.yml
- src/interface/emacs/README.org
- src/interface/emacs/khoj.el
- 9f0bd0a Build khoj.el and Run `package-lint`, `checkdoc` and other [melpa package quality checks](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org#making-your-package-ready-for-inclusion)
- 48ad3c5 Use default content types if fail to call backend on `khoj.el` load
> Add workflow for khoj.el build and quality checks

- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/modal.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- b415f87 Split find and jump to notes code in `onChooseSuggestion` method
- 37063f6 Truncate query to 8k chars for find similar notes from Obsidian plugin
- 4456cf5 No need to use `then` or `finally` in `async` functions after an `await`
- 4070be6 Pass app object from plugin instance to child objects and functions
- c203c6a Use Sentence case for Find Similar Note Obsidian command name
> Resolve Khoj Obsidian Plugin feedback

- README.md
- pyproject.toml
- src/khoj/configure.py
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/khoj_chat.webmanifest
- src/khoj/processor/conversation/gpt.py
- src/khoj/routers/api.py
- src/khoj/routers/api_beta.py
- src/khoj/search_type/image_search.py
- src/khoj/search_type/text_search.py
- tests/test_chatbot.py
- Use the new [API](https://openai.com/blog/introducing-chatgpt-and-whisper-apis) for [ChatGPT](https://openai.com/blog/chatgpt) to improve conversation quality and cost
- Improve Prompt to answer query using indexed notes
- Previously was asking GPT to summarize the notes
- Both the chat and answer API use this new prompt
- Support Multi-Turn conversations
- Pass previous messages and associated reference notes to ChatGPT for context
- Show note snippets referenced to generate response
- Allows fact-checking, getting details
- Simplify chat interface by using only single unified chat type for now
- Replace summarize with answer API. Summarize via API not useful for now
- Only pass Khoj search results above a threshold confidence to GPT for context
- Allows Khoj to say don't know if it …
> Improve Khoj Chat

- src/khoj/processor/conversation/gpt.py
- src/khoj/routers/api.py
- tests/test_chat_actors.py
- tests/test_chat_director.py
Search actor infers Search Queries from user's message
- Capabilities
- Use previous messages to add context to current search queries[^1]
This improves quality of responses in multi-turn conversations. 
- Deconstruct users message into multiple search queries to lookup notes[^2]
- Use relative date awareness to add date filters to search queries[^3]
- Chat Director now does the following:
1. [*NEW*] Use Search Actor to generate search queries from user's message
2. Retrieve relevant notes from Knowledge Base using the Search queries
3. Pass retrieved relevant notes to Chat Actor to respond to user
- Test Search Actor capabilities
- Mark Chat Director Tests for Relative Date, Multiple Search Queries as Expected Pass
- Loosen search results score threshold to work better for searches with …
> Add Search Actor to Improve Querying Notes for Khoj Chat

- src/interface/obsidian/README.md
- src/interface/obsidian/src/chat_modal.ts
- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/search_modal.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- src/interface/obsidian/styles.css
- Set your OpenAI API key in the Khoj Obsidian Settings
- Use Modal in Obsidian for Chat
- Style Chat Modal combining the Khoj Web interface and Obsidian theme style
> Create Chat Modal for Obsidian Plugin

- src/khoj/configure.py
- src/khoj/routers/api.py
- Add try-except-finally blocks around configure calls in `/update`. If the user's configuration isn't correct on initialization, the application still won't start up, but this will at least solve our deadlocking issue when a bad configuration is sent to `/update/`.
> Add try-except-finally blocks around configure calls in /update

- src/khoj/configure.py
- src/khoj/interface/web/processor_conversation_input.html
- src/khoj/processor/conversation/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- src/khoj/routers/api_beta.py
- src/khoj/search_filter/date_filter.py
- src/khoj/utils/config.py
- tests/test_chat_actors.py
- Deprecate the unused beta /answer and /search type identification endpoints and associated GPT functions
- Update extract_questions to use GPT4
- Update summarize method to default to GPT-3.5
- Update date filter to support quoting values in single quotes too. So now both `dt>'2023-04-01'` and `dt>"2023-04-01"` should work
> Move remaining chat actors to use OpenAI chat models

- Dockerfile
- src/khoj/interface/desktop/main_window.py
- src/khoj/main.py
I'm seeing an error when trying to use this image in the Docker container. Work around the package dependency in the Docker installation.
Sample stack trace:
```
khoj-test-image-1 exited with code 1
khoj-test-image-1  | Traceback (most recent call last):
khoj-test-image-1  |   File "/usr/local/bin/khoj", line 5, in <module>
khoj-test-image-1  |     from khoj.main import run
khoj-test-image-1  |   File "/usr/local/lib/python3.10/dist-packages/khoj/main.py", line 24, in <module>
khoj-test-image-1  |     from PySide6 import QtWidgets
khoj-test-image-1  | ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
khoj-test-image-1 exited with code 1
```
> Fix issues importing PySide in Docker container 

- src/khoj/processor/conversation/gpt4all/utils.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- src/khoj/utils/config.py
- Set default behavior to use offline chat if it is enabled.
> Let Offline chat override OpenAI API settings

- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- src/khoj/configure.py
- src/khoj/processor/github/github_to_jsonl.py
- tests/test_client.py
- Add support for configuring/using offline chat (with Llama V2) from within Obsidian
- Fix type checking for search type
Closes https://github.com/khoj-ai/khoj/issues/357
> Add Offline chat to Obsidian

- src/khoj/processor/org_mode/orgnode.py
> Fix typo in orgnode.py

- src/khoj/interface/web/config.html
- src/khoj/processor/conversation/gpt4all/utils.py
- src/khoj/routers/web_client.py
- src/khoj/utils/config.py
- This should help debug issues related to corrupted model download
- If download fails, let the application continue
This should also help mitigate issues, like #379. Should help debug #406
> Add checksums to verify the correct model is downloaded as expected

- docs/README.md
> updated the setup file path to fix the 404 error

- src/khoj/interface/web/chat.html
1. Now we can start a new line with shift&enter.
2. User input can now be displayed on multiple lines.
Closes #409
> Add support for starting a new line with shift-enter

- docs/setup.md
- src/khoj/interface/desktop/main_window.py
- src/khoj/interface/desktop/system_tray.py
- src/khoj/main.py
Reverts khoj-ai/khoj#429
This is causing issues in our desktop packages for MacOS.
> Revert "Open Web interface within Desktop app in GUI mode"

- src/khoj/interface/web/chat.html
- src/khoj/interface/web/index.html
- src/khoj/main.py
- src/khoj/processor/conversation/gpt4all/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- src/khoj/utils/state.py
- tests/conftest.py
- tests/test_client.py
- tests/test_gpt4all_chat_director.py
- tests/test_openai_chat_director.py
- c6b90f7 Move to slash commands instead of using @ to specify general commands
- 01f60ed Add /notes command to respond using only knowledge base as context
> Use Slash Commands and Add Notes Slash Command

- .github/workflows/dockerize.yml
- Dockerfile
- docker-compose.yml
- docs/setup.md
- pyproject.toml
- src/khoj/configure.py
- src/khoj/main.py
- src/khoj/processor/conversation/gpt4all/chat_model.py
- src/khoj/processor/conversation/gpt4all/utils.py
- src/khoj/routers/indexer.py
- tests/test_gpt4all_chat_actors.py
- Remove GPT4All dependency in pyproject.toml. This is because GPT4All is currently unsupported on arm64-based linux machines, which causes builds to fail. On the amd64 machines, recourse to use gpt4all would be to manually install it from within the container. See [this relevant issue](https://github.com/nomic-ai/gpt4all/issues/553).
- Use multiplatform builds in the dockerization setup in GH actions
- Bonus: Be smarter about how content is processed for re-indexing
> Improve docker builds for local hosting

- src/interface/obsidian/src/chat_modal.ts
This merge enable autofocus when chat model is open. This allow the user to chat with Khoj without extra action.
> Autofocus to chat input when openning chat

- pyproject.toml
- src/app/README.md
- src/database/adapters/__init__.py
- src/khoj/processor/embeddings.py
- src/khoj/processor/org_mode/org_to_entries.py
- src/khoj/processor/text_to_entries.py
- src/khoj/routers/indexer.py
- src/khoj/search_type/text_search.py
- src/khoj/utils/cli.py
- tests/test_helpers.py
- tests/test_text_search.py
- Ensure search results logic consistent across migration to DB, multi-user
Manually verified search results for sample queries look the same across migration. Related 5489e98b
- Flatten indexing code for better indexing progress tracking and code readability. Refer dc9946fc, 34b5a86d
- a4f407f5 Test memory leak on MPS device when generating vector embeddings
- ef24485a Improve Khoj with DB setup instructions in the Django app readme (for now)
- f212cc71 Arrange remaining text search tests in arrange, act, assert order
- 022017dd Fix text search tests to test updated indexing log messages
> Improve Indexing Text Entries

- src/interface/desktop/chat.html
- src/khoj/interface/web/chat.html
- Adds a richer experience for showing which notes Khoj used as references to the chat model for response
| Now | Before |
|-|-|
|![Screenshot 2023-10-27 at 10 09 44 AM](https://github.com/khoj-ai/khoj/assets/65192171/a0ec114f-471a-49fa-9bec-295851b2d066)|![Screenshot 2023-10-27 at 10 09 44 AM](https://github.com/khoj-ai/khoj/assets/65192171/2edd8902-eb08-4d78-8378-c8d9232e7d22)|
> Update the chat UI to have richer representation of the references

- src/app/settings.py
- src/database/adapters/__init__.py
- src/interface/desktop/config.html
- src/interface/desktop/main.js
- src/interface/desktop/renderer.js
- src/khoj/interface/web/base_config.html
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/content_source_computer_input.html
- src/khoj/interface/web/search.html
- src/khoj/interface/web/utils.html
- src/khoj/migrations/migrate_server_pg.py
- src/khoj/routers/api.py
- src/khoj/routers/web_client.py
- src/khoj/utils/cli.py
- d6e6ed1c Show next sync time to make users aware of data sync is automated
- d6e6ed1c Keep a single Save button to reduce confusion. It does what Save All
previously did. Intent to manual sync should Save All
- d6e6ed1c Default to using app.khoj.dev as default Khoj URL to ease Cloud sync setup
- 745d6bfe Add detailed chat intro message, mention download desktop app for docs sync
- 6eb7df71 Only show search in web app nav pane if user has documents indexed
- ddac6937 Hide download desktop app message in web app if synced files exist
- 30a9674f Mark generated profile pic with subscription circle in web app
> Reduce Desktop App UX Save, Sync Confusion

- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- src/khoj/routers/indexer.py
- src/khoj/search_type/image_search.py
- src/khoj/utils/rawconfig.py
Update base model definitions for compatibility with new pydantic version
> Update types of base config models for pydantic 2.0

- src/database/adapters/__init__.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/routers/api.py
- src/khoj/search_type/text_search.py
- src/khoj/utils/yaml.py
- a8a25ceac2292e3f7af0005b91b94b4028d99b16: Fix the mechanism for picking the chat model with which to run the `extract_questions` phase of inference
- 5de2ab60988add3fdda0d6aa9f56907fac4f00cb: Use the new `model_validate` method in relevant places
> Fix misc. issues with chat configuration

- pyproject.toml
- src/khoj/main.py
- src/khoj/utils/constants.py
- src/khoj/utils/initialization.py
- c07401cf Fix, Improve chat config via CLI on first run by using defaults
- d61b0dd5 Add Khoj Django app package to sys path to load Django module via pip install
- 4e98acbc Update minimum pydantic version to one with model_validate function
> Improve Self Hosted Khoj Setup

- src/interface/obsidian/src/main.ts
> fix: Fix local server usage

- src/interface/emacs/khoj.el
- 138f4e3f Make auto-update of content index user configurable from khoj.el
- 0885fc6c Handle server unavailable error on auto-index schedule job in khoj.el
Resolves #567
> Handle Server Unavailable Error from Khoj.el

- src/khoj/app/settings.py
- src/khoj/database/admin.py
- src/khoj/routers/api.py
- Fixes error message if text to image config not set
- Fixes how the CSRF cookie is being set for the django settings
> Fix image generation setup bug and CSRF cookie for admin login

- src/interface/desktop/chat.html
- src/khoj/interface/web/chat.html
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- Add inferred queries to improve image generation
- Render said inferred query with the returned image
- Improve the generated help text and add markdown formatting
> Improvements to chat functionality and image generation

- src/khoj/routers/api.py
Changed @app.get("/health") to @api.get("/health")
used the Response class and set the input for for status_code to 200 and also remove the comment.
> Fixed health check to khoj api

- docs/_sidebar.md
- docs/development.md
Add better instructions for how to get setup as a contributor to the Khoj repo
> Improve the developer documentation

- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- src/khoj/routers/api.py
- 870af19b Update health API to pass authenticated users their info
- fe8b7f18 Improve Khoj server status check in Khoj Obsidian client
- 8d4155be Show Khoj Obsidian commands even if no connection to server
- 461a925f Show Khoj chat by default in Obsidian side pane instead of search
> Improve server status check and message in Obsidian client

- src/khoj/database/adapters/__init__.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- Include conversation history so that subqueries or intermediate prompts are generated with the appropriate context
> Improve subqueries for online search and prompt generation for image

- src/khoj/configure.py
- src/khoj/database/adapters/__init__.py
- Correctly use the code to get the current subscription state
> Fix subscription state detection for users based on phone numbers, emails

- src/interface/desktop/main.js
- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- src/khoj/interface/web/base_config.html
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/content_source_computer_input.html
- src/khoj/interface/web/content_source_github_input.html
- src/khoj/interface/web/content_source_notion_input.html
- src/khoj/interface/web/search.html
- src/khoj/interface/web/utils.html
- src/khoj/routers/web_client.py
- src/khoj/search_type/text_search.py
- Only send files modified since their last sync for indexing on server from the Obsidian client
- Invalidate static asset browser cache in Web client when Khoj version changes
> Improve Syncing Obsidian Vault

- src/khoj/database/admin.py
- src/khoj/processor/content/text_to_entries.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/tools/online_search.py
- Simplify the prompt for getting dynamic tool selection cfb50a14f0fad424e5b06f44ab3a37778663ad74
- Add error handling when calling `OLOSTEP` fb14cabbdcfa82561ad1fe2649aa6575bdd8e355
- Remove `conversation_id` search field from admin page filter  133a1b6dade2f576d6b0a23e48f941d541eb5129
> Misc. fixes to prompting, admin, and others

- src/interface/desktop/chat.html
- src/interface/desktop/config.html
- src/interface/desktop/main.js
- src/interface/desktop/renderer.js
- src/khoj/interface/web/chat.html
- src/khoj/processor/conversation/prompts.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- tests/test_gpt4all_chat_actors.py
- tests/test_gpt4all_chat_director.py
- tests/test_openai_chat_actors.py
- tests/test_openai_chat_director.py
- Add online context and user notes in the image generation flow
- Allow the agent to dynamically determine whether to return the response as an image or as text
- Render references when included as part of image generation in web, desktop chat views
> Include additional user context in the image generation flow

- pyproject.toml
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- tests/test_helpers.py
- 38238a50 Read web pages in parallel to improve chat response time
- 094f3c93 Read web pages directly when Olostep proxy not setup
- bd35ff38 Include search results & web page content in online context for chat response
- 14c1d688 Simplify, modularize and add type hints to online search functions
> Improve Online Search Speed and Context

- src/interface/desktop/chat.html
- src/interface/desktop/main.js
- src/khoj/interface/web/chat.html
- 49cae6a4 Make valid file extension checking case insensitive on Desktop app
- 48d4bf18 Skip indexing non-existent folders on Desktop app
- 502bb477 Pass auth headers to fix lazy load of chat messages on Desktop app
- 34bfef0b Set chat-message height to height of content in web, desktop
> Fix Chat UI and Indexing on Desktop App

- pyproject.toml
- src/khoj/processor/conversation/offline/utils.py
- src/khoj/processor/conversation/prompts.py
- tests/test_offline_chat_actors.py
- a2e4e4be Add support for Llama 3 in Khoj offline mode
- 4f7237b1 Make chat actors generate valid json with more local models
- f2db8d7d Fix offline chat actor tests
> Support Llama 3 and Improve Offline Chat Actors

- src/interface/desktop/chat.html
- src/khoj/interface/web/base_config.html
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/config.html
- src/khoj/routers/api.py
- src/khoj/routers/api_chat.py
- 12a5c582 Add section in settings page to view, delete your scheduled tasks
- 4a44280f Add API endpoints to get and delete user scheduled tasks
- 088d2c00 Save separate user message time from Khoj response time in chat logs
- 36eead12 Minor improvements to styling the config page
- 52b28cce Suffix chat response element vars with "El" in chat.html of web, desktop apps
> Add UX to Configure Scheduled Tasks (Reminders: Part 3)

- src/khoj/interface/web/chat.html
- src/khoj/interface/web/config_automation.html
- src/khoj/interface/web/public_conversation.html
- Make the cards more intuitive
- Add suggested automations to better explain how the feature works
- Bonus: fix math rendering filters
| Before | After |
|-|-|
| <img width="1084" alt="Screenshot 2024-05-08 at 13 45 01" src="https://github.com/khoj-ai/khoj/assets/65192171/66455e23-cdde-4c84-81a4-3ca5986c6d85"> |<img width="1855" alt="Screenshot 2024-05-09 at 01 16 50" src="https://github.com/khoj-ai/khoj/assets/65192171/8b66f540-c546-4d55-90d9-b7efb47c4231"> |
> Improve the UX of automations

- documentation/docs/clients/desktop.md
> docs: update desktop.md

- documentation/docs/contributing/development.mdx
* Added Postgres installation process to development page.
* Created Windows Development Notes section with potential errors encountered during installation and their corresponding fixes.
> Documentation Fixes for Development Page

- src/khoj/app/settings.py
- src/khoj/interface/web/config_automation.html
- src/khoj/main.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
Disable setting recurrence of automations to less than an hourly frequency.
Checks crontime string for minutely recurrence and either
- Sets it to run at a a random minute of the hour
- Throws error for user to fix their request
> Disable Minutely Recurrence for Automations

- src/khoj/interface/web/base_config.html
- src/khoj/interface/web/config_automation.html
- src/khoj/routers/api.py
- src/khoj/routers/auth.py
- src/khoj/routers/web_client.py
- Add UI support for rendering shareable automation
- Use URL params to update the view with the automation config
- Allow it to be viewed, even if the user is unauthenticated
- If adding automation when not logged in, prompt to login
> Allow automations to be shareable

- documentation/docs/clients/web.md
- documentation/docs/data-sources/share_your_data.md
- documentation/docusaurus.config.js
- src/interface/desktop/search.html
- src/khoj/database/adapters/__init__.py
- src/khoj/database/management/commands/change_generated_images_url.py
- src/khoj/database/management/commands/serve_generated_images_from_server.py
- src/khoj/interface/web/chat.html
- src/khoj/interface/web/login.html
- src/khoj/routers/storage.py
- f6ce9ff2 Serve generated images from Khoj domain instead of directly from S3
- 274b1e71 Rename assets URL from Khoj S3 bucket to assets.khoj.dev
> Serve image assets from Khoj domain, not directly from S3 bucket

- src/khoj/interface/web/login.html
- See migration guidelines here: https://developers.google.com/identity/gsi/web/guides/fedcm-migration#fedcm_flag
> Add fedCM to accommodate google migration

- src/interface/obsidian/src/chat_view.ts
- src/interface/obsidian/src/main.ts
- src/interface/obsidian/src/pane_view.ts
- src/interface/obsidian/src/utils.ts
- src/interface/obsidian/styles.css
- Simplify quick jump between Khoj side pane and main editor view using keyboard shortcuts
- Enable voice chat in Obsidian to make interactions with Khoj more seamless
> Enable Voice, Keyboard Shortcuts in Khoj Obsidian Plugin

- src/interface/obsidian/src/search_modal.ts
- src/interface/obsidian/src/settings.ts
- src/interface/obsidian/src/utils.ts
- tests/test_client.py
- Sync images from Obsidian vault with Khoj server now that Khoj can OCR images
- Support rendering images returned by Khoj search modal
> Support syncing, searching images from Obsidian plugin

- src/interface/web/app/automations/automations.module.css
- src/interface/web/app/automations/page.tsx
- src/interface/web/app/components/shareLink/shareLink.tsx
> Update automations UX for more consistency

- src/interface/web/app/settings/page.tsx
- src/interface/web/app/settings/settings.module.css
- src/interface/web/package.json
- src/interface/web/yarn.lock
- src/khoj/routers/helpers.py
- Link up the different states and endpoints for WhatsApp linking/number verification
- Use a friendly phone number input field for country codes. See https://github.com/jackocnr/intl-tel-input/.
> Use international phone number input and verify whatsapp flow

- src/khoj/processor/conversation/anthropic/anthropic_chat.py
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- tests/test_openai_chat_actors.py
- 75f7e701 Improve doc search actor performance on vague, random or meta questions
- a47a54f2 Pass user's name to document and online search actors prompts
- 878cc023 Fix and improve openai chat actor tests
- f393663d Remove unused max tokns arg to extract qs func of doc search actor
> Improve Document, Online Search to Answer Vague or Meta Questions

- src/khoj/routers/api_content.py
- tests/test_client.py
Increase the subscribed rate limit to 200MB
> Increase rate limits for data indexing

- src/interface/desktop/chat.html
- src/interface/desktop/main.js
- src/interface/desktop/preload.js
Fixed when user clicks on open khoj web settings for api token its been redirected to incorrect url hostUrl/config instead of hostUrl/settings @sabaimran @debanjum
> Fix URL to web, desktop settings pages on Desktop application 

- src/interface/web/app/components/chatMessage/chatMessage.module.css
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/helpers.py
- The new O1 series doesn't seem to support streaming, response_format enforcement, 
stop words or temperature currently. 
- Remove any markdown json codeblock in chat actors expecting json responses
- Override block display styling of links by Katex in chat messages
> Support OpenAI's new O1 Model Series

- src/khoj/interface/web/login.html
|Before|After|
|-|-|
|![Screenshot 2024-10-02 at 14 13 51](https://github.com/user-attachments/assets/77201a8f-d24c-4678-b7dd-dd4b4ed1e8d2)|![Screenshot 2024-10-02 at 14 13 32](https://github.com/user-attachments/assets/06dc8036-9d5d-481b-991f-690ef1678b47)|
> Improve the login page

- src/interface/desktop/chat.html
- src/interface/desktop/shortcut.html
- src/interface/obsidian/src/chat_view.ts
- src/interface/web/app/automations/page.tsx
- src/interface/web/app/chat/page.tsx
- src/interface/web/app/common/utils.ts
- src/interface/web/app/share/chat/page.tsx
- src/khoj/processor/conversation/anthropic/anthropic_chat.py
- src/khoj/processor/conversation/google/gemini_chat.py
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/tools/online_search.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/helpers.py
- src/khoj/utils/rawconfig.py
Add user country code as context for doing online search with serper.dev API.
This should find more user relevant results from online searches by Khoj
- Default to using system clock to infer user timezone on js clients
- Infer country from timezone when only timezone received by chat API
- Localize online search results to user country when location available
- Add `__str__` func to `LocationData` class to deduplicate location string generation
> Make Online Search Location Aware

- src/khoj/processor/conversation/anthropic/anthropic_chat.py
- src/khoj/processor/conversation/anthropic/utils.py
- src/khoj/processor/conversation/google/utils.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api.py
- src/khoj/routers/helpers.py
- Give Vision to Anthropic models in Khoj
- Reuse logic to format messages for chat with anthropic models
- Make the get image from url function more versatile and reusable
- Encourage output mode chat actor to output only json and nothing else
> Give Vision to Anthropic models in Khoj

- .github/workflows/run_evals.yml
- src/interface/obsidian/src/chat_view.ts
- src/interface/web/app/common/chatFunctions.ts
- src/khoj/processor/conversation/anthropic/utils.py
- src/khoj/processor/conversation/google/utils.py
- src/khoj/processor/conversation/openai/utils.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- src/khoj/utils/constants.py
- src/khoj/utils/helpers.py
- tests/evals/eval.py
- Track, return cost and usage metrics in chat api response
Track input, output token usage and cost of interactions with 
openai, anthropic and google chat models for each call to the khoj chat api
- Collect, display and store costs & accuracy of eval run currently in progress
This provides more insight into eval runs during execution 
instead of having to wait until the eval run completes.
> Track Usage Metrics in Chat API. Track Running Cost, Accuracy in Evals

- src/khoj/processor/conversation/anthropic/anthropic_chat.py
- src/khoj/processor/conversation/google/gemini_chat.py
- src/khoj/processor/conversation/offline/chat_model.py
- src/khoj/processor/conversation/openai/gpt.py
- src/khoj/processor/conversation/prompts.py
- src/khoj/processor/conversation/utils.py
- src/khoj/routers/api_chat.py
- src/khoj/routers/helpers.py
- tests/test_online_chat_actors.py
- Use the generated descriptions / inferred queries to supply context to the model about what it's created and give a richer response
- Stop sending the generated image in user message. This seemed to be confusing the model more than helping.
- Collect generated assets in a structured objects to provide model context. This seems to help it follow instructions and separate responsibility better
- Also, rename the open ai converse method to converse_openai to follow patterns with other providers
> Improve handling of multiple output modes

- src/khoj/database/admin.py
- src/khoj/processor/conversation/openai/utils.py
fix AttributeError: 'NoneType' object has no attribute 'model_extra'
https://github.com/khoj-ai/khoj/issues/1019
> Handle reporting chat estimated cost when some fields unavailable

- documentation/docs/advanced/admin.md
> docs: update admin.md

- src/khoj/processor/tools/online_search.py
Add official Google Search API as an online search provider.
We currently support Serper.dev and Searxng as online search providers.
> Support online search using Google Search API

- documentation/docs/features/automations.md
> docs: update automations.md

- documentation/docs/contributing/development.mdx
corrected a typo in the "Development" section where "you" should have been "your," and "interesting" should be "interest."
thnks!
> Fix typo in Development documentation

- src/interface/web/app/agents/layout.tsx
- src/interface/web/app/automations/layout.tsx
- src/interface/web/app/chat/layout.tsx
- src/interface/web/app/common/modelSelector.tsx
- src/interface/web/app/components/chatHistory/chatHistory.tsx
- src/interface/web/app/components/chatSidebar/chatSidebar.tsx
- src/interface/web/app/layout.tsx
- src/interface/web/app/search/layout.tsx
- src/interface/web/app/settings/layout.tsx
- src/interface/web/app/settings/page.tsx
- src/interface/web/app/share/chat/layout.tsx
- Set chatSidebar prompt, Setting name fields to empty str if value null
- Track if agent modified in chatSidebar to simplify code, fix looping
- Suppress spurious dark mode hydration warnings on the web app
- Set key for chatMessage parent to get UX efficiently updated by react
- Let only root next.js layout handle html, body tags, not child layouts
> Fix and Improve Chat sidebar and component setup on Web App

- README.md
- documentation/docs/advanced/gcp-vertex.md
Contribution Description
Added a helpful “Troubleshooting & Tips” section to the gcp-vertex.md documentation.
This section provides guidance for self-hosted users on common issues they may encounter when setting up Google Vertex AI integration in Khoj. Topics covered include permissions, region compatibility, prompt size limits, API key testing, and secure key management with environment variables. The goal is to improve the onboarding experience and reduce setup errors for contributors and self-hosters using Vertex AI models like Claude and Gemini.
Signed off by: brightally6@gmail.com
> Add FAQ section to Readme and Troubleshooting Tips to setup GCP Vertex

- src/interface/obsidian/src/chat_view.ts
The function createNewConversation is never called with the agentSlug specified so its always opening a new Conversation with the Base Agent
> Fix to create chat with custom agents from obsidian
